<?php if( have_rows('section-consultants') ):

	while( have_rows('section-consultants') ): the_row();

		// vars
    $subheading = get_sub_field('subheading');
    $heading = get_sub_field('heading');
    $paragraph = get_sub_field('paragraph');
		$btnlink = get_sub_field('btn_link');
		$url = $btnlink["url"];
		$label = $btnlink["title"];
		?>
    <div class="grid consultants-sm section-6rem">
      <div class="row">
        <div class="ly--col-lg-12 section-heading">
          <h5 class="sub-heading-three"><?= $subheading ?></h5>
          <h2 class="heading-three"><?= $heading ?></h2>

        </div>
        <div class="ly--col-lg-6 ly--col-sm-12 section-wrap section-left">
             <p><?= $paragraph ?></p>
							 <a class="btn btn-primary" href="<?= $url ?>"><?= $label ?></a>
        </div>

        <div class="ly--col-lg-6 ly--col-sm-12 section-wrap">

          <?php
                $args = array(
                    'post_type' => 'consultants',
                    'orderby' => 'title',
                    'order'   => 'DESC',
                    'posts_per_page' => -1,
                );

                $query = new WP_Query( $args );
                ?>

                <?php while ( $query->have_posts() ) : $query->the_post();?>

									<div class="section-2col revealer-<?= $i++ * 100 ?>">

										<?php include( get_template_directory() . '/phtml/sections/cards/card-consultant.phtml');?>

									</div>

                <?php endwhile; ?>

                <?php
                wp_reset_postdata();?>

        </div>

      </div>
    </div>
	<?php endwhile; ?>

<?php endif; ?>
