<?php if( have_rows('section-consultants') ):

	while( have_rows('section-consultants') ): the_row();

		// vars
    $subheading = get_sub_field('subheading');
    $heading = get_sub_field('heading');
    $paragraph = get_sub_field('paragraph');
		$btnlink = get_sub_field('btn_link');
		$url = $btnlink["url"];
		$label = $btnlink["title"];
		?>
    <div class="bx--grid consultants-sm section-4rem">
      <div class="bx--row">
        <div class="bx--col-lg-12 section-heading">
          <h5 class="bx--type-delta__subheading"><?= $subheading ?></h5>
          <h2 class="bx--type-alpha"><?= $heading ?></h2>

        </div>
        <div class="bx--col-lg-6 bx--col-sm-12 section-wrap section-left">
             <p><?= $paragraph ?></p>
						 <div class="padding-top">
							 <a href="<?= $url ?>"><button class="bx--btn bx--btn__secondary" type="button"><?= $label ?></button></a>
						 </div>
        </div>

        <div class="bx--col-lg-6 bx--col-sm-12 section-wrap">

          <?php
                $args = array(
                    'post_type' => 'consultants',
                    'orderby' => 'title',
                    'order'   => 'DESC',
                    'posts_per_page' => -1,
                );

                $query = new WP_Query( $args );
                ?>

                <?php while ( $query->have_posts() ) : $query->the_post();?>

									<div class="section-2col">

										<?php include( get_template_directory() . '/phtml/sections/cards/card-consultant.phtml');?>

									</div>

                <?php endwhile; ?>

                <?php
                wp_reset_postdata();?>
								<!-- <div class="bx--col-sm-12">
									<input class="toggle toggle-ios" id="cb2" type="checkbox"/>
									<label class="toggle-btn" for="cb2"></label>
								</div> -->
        </div>

      </div>
    </div>
	<?php endwhile; ?>

<?php endif; ?>
