<div class="bx--grid cta-section secondary">
  <div class="bx--row">
    <div class="bx--col cta-section-container">

      <div class="text-container">
        <h3 class="text-container_heading">En heading om något spännande</h3>
        <p class="text-container_paragraph">En paragraf om något spännande som ingen riktigt förstår </p>
      </div>

      <button class="bx--btn bx--btn__secondary" type="button">
        Primary with icon
        <svg class="bx--btn__icon" width="16" height="16" viewBox="0 0 16 16" fill-rule="evenodd">
          <path d="M8 0C3.6 0 0 3.6 0 8s3.6 8 8 8 8-3.6 8-8-3.6-8-8-8zm4 9H9v3H7V9H4V7h3V4h2v3h3v2z"></path>
        </svg>
      </button>

    </div>

  </div>
</div>
