<?php
  $animate = get_field('animated_post');
?>
<a class="card-link" href="<?= the_permalink(); ?>">
    <div class="card card-service">

      <div class="service-img-container">

        <?php if( get_the_post_thumbnail_url() ): ?>
          <img src="<?= get_the_post_thumbnail_url(); ?>" class="service-img" alt="" />
        <?php endif; ?>

      </div>

      <div class="service-text-container">
        <h3 class="heading-five service-heading">
          <?= get_the_title(); ?>
          <?php if ( $animate == 1):?>
            <span class="ly--tag ly--tag--digital-tillvaxt">Börja här</span>
          <?php endif;?>
        </h3>
        <p class="paragraph-sm no-margin"><?= get_the_excerpt(); ?></p>
      </div>

      <?php if ( $animate == 1):?>
        <span class="pulse-lg topleft"></span>
      <?php endif;?>

    </div>
	</a>
