<div class="ly--form-item">
  <label for="text1" class="ly--label">Text Input label</label>
  <input id="text1" type="text" class="ly--text-input" placeholder="Placeholder text" />
  <div class="ly--form-requirement">
    Username is taken.
  </div>
</div>
<div class="ly--form-item">
  <label for="text-area-2" class="ly--label">Text area label</label>
  <textarea id="text-area-2" class="ly--text-area" rows="4" cols="50" placeholder="Placeholder text"></textarea>
  <div class="ly--form-requirement">
    Please do not leave blank.
  </div>
</div>
<div class="ly--form-item">
  <label for="select-id-form" class="ly--label">Select label</label>
  <div class="ly--select">
    <select id="select-id-form" class="ly--select-input">
      <option class="ly--select-option" disabled selected hidden>Choose an option</option>
      <option class="ly--select-option" value="solong">A much longer option that is worth having around to check how text flows</option>
      <optgroup class="ly--select-optgroup" label="Category 1">
        <option class="ly--select-option" value="option1">Option 1</option>
        <option class="ly--select-option" value="option2">Option 2</option>
      </optgroup>
      <optgroup class="ly--select-optgroup" label="Category 2">
        <option class="ly--select-option" value="option1">Option 1</option>
        <option class="ly--select-option" value="option2">Option 2</option>
      </optgroup>
    </select>
    <div class="ly--form-requirement">
      Please choose an option.
    </div>
    <svg class="ly--select__arrow" width="10" height="5" viewBox="0 0 10 5" fill-rule="evenodd">
      <path d="M10 0L5 5 0 0z"></path>
    </svg>
  </div>
</div>
<div class="ly--form-item">
  <button class="ly--btn ly--btn__primary" type="button">Submit</button>
</div>
