<div class="hero hero-sm" style=" background-image: url(

    <?php if ( is_page(20) ) {
            echo get_field('hero_image');

        } elseif ( is_home() ) { // Learn without latest post as bg image
            echo get_field('hero_image',get_option('page_for_posts'));

        } else if ( get_field('hero_image') )  { // Pillar & Landing pages
            echo get_field('hero_image');
        } else {
            $bg_thumbnail = get_the_post_thumbnail_url(get_the_ID(),'full');
            echo $bg_thumbnail;
        }
      ?>);">
    <?php if (!is_page(86)): ?>
      <div class="overlay" style="opacity: 0.3 <?php echo get_field('opacity');?>;"></div>
    <?php endif;?>

    <div class="bx--col-xs-12 bx--col-md-12 hero-content">
      <?php if ( is_singular('post') ) :?>
            <h1 class="bx--type-beta type-white">
      <?php else :?>
            <h1 class="bx--type-giga type-white">
      <?php endif;?>
          <?php if ( get_the_ID() == 86 ) {

                } elseif ( is_home() ) {
                  echo get_field('hero_heading',get_option('page_for_posts'));

                } else {
                  echo esc_html( get_the_title() );
                }
              ?>
        </h1>
    </div>
</div>
