<div class="test-header"></div>
<div class="test-nav"></div>
<header data-detail-page-header class="ly--detail-page-header ly--detail-page-header--no-tabs">
  <div class="ly--detail-page-header-content">
    <div class="ly--breadcrumb">
      <div class="ly--breadcrumb-item">
        <a href="#" class="ly--link">Breadcrumb 1</a>
      </div>
      <div class="ly--breadcrumb-item">
        <a href="#" class="ly--link">Breadcrumb 2</a>
      </div>
      <div class="ly--breadcrumb-item">
        <a href="#" class="ly--link">Breadcrumb 3</a>
      </div>
    </div>
    <div class="ly--detail-page-header-title-container">
      <div class="ly--detail-page-header-icon-container">
        <svg width="24" height="24" viewBox="0 0 24 24">
          <path fill="#D8D8D8" d="M0 0h24v24H0z" fill-rule="evenodd" />
        </svg>
      </div>
      <h1 class="ly--detail-page-header-title">Title</h1>
      <div class="ly--detail-page-header-status-container">
        <div class="ly--detail-page-header-status-icon"></div>
        <span class="ly--detail-page-header-status-text">Running</span>
      </div>
    </div>
  </div>
  <div class="ly--detail-page-header-menu">
    <div data-overflow-menu tabindex="0" aria-label="Overflow menu description" class="ly--overflow-menu">
      <svg class="ly--overflow-menu__icon" width="4" height="20" viewBox="0 0 4 20" fill-rule="evenodd">
        <circle cx="2" cy="2" r="2"></circle>
        <circle cx="2" cy="10" r="2"></circle>
        <circle cx="2" cy="18" r="2"></circle>
      </svg>
      <ul class="ly--overflow-menu-options ly--overflow-menu--flip">
        <li class="ly--overflow-menu-options__option">
          <button class="ly--overflow-menu-options__btn">Stop app</button>
        </li>
        <li class="ly--overflow-menu-options__option">
          <button class="ly--overflow-menu-options__btn">Restart app</button>
        </li>
        <li class="ly--overflow-menu-options__option">
          <button class="ly--overflow-menu-options__btn">Rename app</button>
        </li>
        <li class="ly--overflow-menu-options__option">
          <button class="ly--overflow-menu-options__btn">Edit routes and access</button>
        </li>
        <li class="ly--overflow-menu-options__option ly--overflow-menu-options__option--danger">
          <button class="ly--overflow-menu-options__btn">Delete app</button>
        </li>
      </ul>
    </div>
  </div>
</header>
