<div class="grid preloader">
  <div class="row">
    <div class="preloader--container">
      <img class="preloader__image" src="<?=get_stylesheet_directory_uri(); ?>/images/lyfter-preloader.svg" />
      <!-- <img class="preloader__image" src="https://media.giphy.com/media/3oKIPtjElfqwMOTbH2/giphy.gif" /> -->
      <div class="bar"><div class="progress"></div></div>
      <p class="paragraph-xs center light"><span class="counter">0</span> %</p>
    </div>

    <!-- <div class="wipe wipe-1"></div>
    <div class="wipe wipe-2"></div>
    <div class="wipe wipe-3"></div>
    <div class="wipe wipe-4"></div> -->

  </div>
</div>
