<?php if( have_rows('advantages') ):

        while( have_rows('advantages') ): the_row();?>
          <div class="bx--grid section-default bg-03">

              <div class="bx--row section-center--col">
                <h6 class="revealer-0"><?= get_sub_field('subheading'); ?></h6>
                <h3 class="bx--type-beta"><?= get_sub_field('heading'); ?></h3>
              </div>

              <div class="bx--row">
    <?php if( have_rows('card') ):

            while ( have_rows('card') ) : the_row();
            ?>

          <div class="bx--col-xs-12 bx--col-md-6 bx--col-lg-4 section-3col--card">

            <div class="card-sm revealer-0">
                  <div class="card-img image card-half">
                    <div class="img-container--icon bg-img--acf" style="background-image: url('<?= get_sub_field('bg_image');?>');">
                        <img class="icon revealer-100" style="height: <?= get_sub_field('icon_size');?>px" alt="<?= get_sub_field('alt_text'); ?>" src="<?= get_sub_field('icon'); ?>"/>
                        <div class="overlay" style="opacity:<?= get_sub_field('overlay_opacity');?>;"></div>
                    </div>
                  </div>

                  <div class="card-content card-half">
                    <div class="text-container">
                      <h3><?= get_sub_field('sub-heading');?></h3>
                      <p><?= get_sub_field('paragraph');?></p>
                    </div>
                  </div>
              </div>
          </div>

        <?php  endwhile;

      else :

          // no rows found

      endif;

      ?>

      </div>
    </div>

	<?php endwhile;

        endif; ?>
