<?php
  if (is_home()):
    $subheading = get_field('sub-heading', $page_for_posts);
    $heading = get_field('heading', $page_for_posts);
    $paragraph = get_field('paragraph', $page_for_posts);
  else:
    $subheading = get_field('sub-heading');
    $heading = get_field('heading');
    $paragraph = get_field('paragraph');
  endif;
?>
<div class="bx--grid hero">
  <div class="bx--row">
    <div class="bx--col-xs-12 bx--col-md-6 hero-container">
        <h5 class="bx--type-gamma_subheading hero-subheading"><?= $subheading ?></h5>
        <h2 class="bx--type-mega hero-heading"><?= $heading ?></h2>
        <p class="bx--type-delta_paragraph hero-paragraph"><?= $paragraph ?></p>
    </div>
    <?php if( get_field('image') ): ?>
      <img src="<?php the_field('image'); ?>" class="hero-image" alt="" />
    <?php endif; ?>
  </div>
</div>
