<?php
  if (is_home()):
    $subheading = get_field('sub-heading', $page_for_posts);
    $heading = get_field('heading', $page_for_posts);
    $paragraph = get_field('paragraph', $page_for_posts);
    $herobgimg = get_field('background-image', $page_for_posts);
    $curvesimg = get_field('curves_image', $page_for_posts);
    $overlaycolor = get_field('overlay_color', $page_for_posts);
    $overlayopacity = get_field('overlay_opacity', $page_for_posts);
  else:
    $subheading = get_field('sub-heading');
    $heading = get_field('heading');
    $paragraph = get_field('paragraph');
    $herobgimg = get_field('background_image');
    $curvesimg = get_field('curves_image');
    $overlaycolor = get_field('overlay_color');
    $overlayopacity = get_field('overlay_opacity');
  endif;
?>
<?php if ( $post->post_type == 'post' && !is_home() ): ?>

            <div class="bx--grid section-content__outer">
                <div class="bx--row">

                    <div class="section-content">

                      <!-- Author information card -->
                      <?php include( get_template_directory() . '/phtml/sections/author-info/author-info__sm.phtml'); ?>

                      <div class="h2-section">
                        <h1 class="heading-two"><?= the_title() ?></h1>
                      </div>

                      <div class="ingress">
                        <p class="paragraph"><?= get_field('ingress'); ?></p>
                      </div>

                    </div>
                </div>
            </div>
            <div class="section-post-image img-container">

                          <?php  $img = get_field('fullwidth_image');

                                  if( !empty($img) ):

                                    echo add_image(
                                      $img,  // ACF-field
                                      'q_70', // Parameters
                                      'post-image featured-image' // Classes
                                    );

                                  endif; ?>

            </div>

<?php elseif ( is_page_template('page-templates/about-us.php') ):?>

  <?php if ($herobgimg):?>
    <div class="bx--grid hero about-us hero__bg-image" style="background-image: url('<?php add_bg_image($herobgimg, 'g_south,q_60,c_fill,w_1280');?>');">
  <?php else:?>
    <div class="bx--grid hero">
  <?php endif;?>
      <div class="bx--row">
        <div class="bx--col-xs-12 bx--col-md-8 hero-container">
            <h5 class="sub-heading-one hero-subheading"><?= $subheading ?></h5>
            <h1 class="heading-one hero-heading"><?= $heading ?></h1>
        </div>
      </div>
    </div>


<?php elseif ( is_singular('services') ):?>

  <?php if ($herobgimg):?>
    <div class="bx--grid hero hero__bg-image" style="background-image: url('<?php add_bg_image($herobgimg, 'g_south,q_60,c_fill,w_1280');?>');">
  <?php else:?>
    <div class="bx--grid hero services">
  <?php endif;?>
      <div class="bx--row">

        <div class="bx--col-lg-12 hero-container">
          <div class="hero--image-container">
            <?php add_thumbnail_image('g_south,q_60,c_fill,w_1280', '');?>
          </div>

          <div class="hero--text-container">
            <h5 class="sub-heading-two hero-subheading">TJÄNSTER</h5>
            <h1 class="heading-two hero-heading"><?= the_title() ?></h1>
          </div>

        </div>


      </div>
    </div>

<?php elseif ( is_singular('consultants') ):?>

  <?php if ($herobgimg):?>
    <div class="bx--grid hero hero__bg-image" style="background-image: url('<?php add_bg_image($herobgimg, 'g_south,q_60,c_fill,w_1280');?>');">

  <?php else:?>
    <div class="bx--grid hero consultants">
  <?php endif;?>
      <div class="bx--row">

        <div class="bx--col-lg-12 hero-container">
            <h5 class="sub-heading-two hero-subheading">Konsultroll</h5>
            <h1 class="heading-two hero-heading"><?= the_title() ?></h1>
        </div>

      </div>
    </div>

<?php else: ?>
  <?php if ($herobgimg):?>
    <div class="bx--grid hero hero__bg-image" style="background-image: url('<?php add_bg_image($herobgimg, 'g_south,q_60,c_fill,w_1280');?>');">
  <?php else:?>
    <div class="bx--grid hero">
  <?php endif;?>
    <div class="bx--row">
      <div class="bx--col-xs-12 bx--col-md-10 bx--col-lg-6 hero-container">
          <h5 class="sub-heading-two hero-subheading light"><?= $subheading ?></h5>
          <h1 class="heading-two hero-heading light"><?= $heading ?></h1>
          <p class="paragraph hero-paragraph light"><?= $paragraph ?></p>
      </div>
      <?php if( get_field('image') ): ?>

        <?php  $img = get_field('image');

                if( !empty($img) ):

                  echo add_image(
                    $img,  // ACF-field
                    'g_south,q_60,c_fill,w_1280', // Parameters
                    'hero-image' // Classes
                  );

                endif; ?>

      <?php endif; ?>
    </div>

    <div class="hero--overlay" style="background: <?= @$overlaycolor ?>; opacity: <?= @$overlayopacity ?>;"></div>

    <div class="hero--curves">
      <img src="<?= $curvesimg ?>">
    </div>

  </div>

<?php endif; ?>
