<?php if( have_rows('hero_career') ): ?>

	<?php while( have_rows('hero_career') ): the_row();

		// vars
		$subheading = get_sub_field('subheading');
		$heading = get_sub_field('heading');
		$paragraph = get_sub_field('paragraph');
    $link = get_sub_field('btn');
    $btnlink = $link['url'];
    $btnlabel = $link['title'];
    $bgimg = get_sub_field('background_image');

		?>
    <div class="grid hero hero--career hero__bg-image" style="background-image: url('<?= $bgimg ?>');">
      <div class="row">

        <div class="ly--col-xs-12 ly--col-md-12 ly--col-lg-8 hero--container">
            <h5 class="ly--type-gamma__subheading hero__subheading"><?= $subheading ?></h5>
            <h1 class="heading-one hero__heading"><?= $heading ?></h1>
            <p class="ly--type-delta__paragraph hero__paragraph"><?= $paragraph ?></p>
        </div>

        <!-- CTA button -->
        <a class="btn--career" href="<?= $btnlink ?>">
          <button class="ly--btn ly--btn__secondary ly--btn--lg btn--contact" type="button">
            <?= $btnlabel ?>
            <svg class="ly--btn__icon" width="16" height="16" viewBox="0 0 16 16" fill-rule="evenodd">
              <polygon fill="#FFFFFF" fill-rule="evenodd" points="134 14 137.682 21.365 144.667 22.001 137.682 22.635 134 30 150 22.001" transform="translate(-134 -14)"/>
            </svg>
          </button>
        </a>

      </div>
    </div>

	<?php endwhile; ?>



<?php endif; ?>
