<a class="card-link" href="<?= the_permalink(); ?>">
	<div class="card card-consultant revealer-100">
    <div class="consultants-text-container">
      <h4 class="heading-five no-margin consultants-heading"><?= get_the_title(); ?></h4>
    </div>
	<img class="card-consultant__img" src="https://res.cloudinary.com/agrowth/image/upload/v1541809310/agrowth-profile-victor_transparent_hqhqp0.png" />
  </div>
</a>
