<a class="card-link" href="<?php echo get_permalink( $post->ID ); ?>">

  <div class="card card-post">

    <div class="card-img image card-half">
      <div class="img-container">
          <?php add_thumbnail_image('g_south,q_60,c_fill,w_700', 'featured-image');?>
      </div>
    </div>

    <div class="card-content card-half">
      <div class="text-container">

            <h4 class="title bx--type-gamma__paragraph"><?php the_title();?></h4>

      </div>
      <div class="info-container">
        <div class="info-container--part">
          <img class="icon icn-clock" src="<?php bloginfo('template_url'); ?>/icons/icn-clock.svg" />
          <p class="bx--type-zeta">6 min läsning</p>
        </div>
        <div class="info-container--part">
          <img class="icon icn-clock" src="<?php bloginfo('template_url'); ?>/icons/ui-icons/icn-date.svg" />
          <p class="bx--type-zeta"><?= get_the_date("j F, Y");?></p>
        </div>
      </div>
            <div class="tag-container">

            <?php foreach ( ( get_the_category() ) as $category ):
                $catname = $category->name;
                $catslug = $category->slug;
              ?>
              <span class="bx--tag bx--tag--<?= $catslug ?>"><?= $catname ?></span>
              <?php endforeach;?>
            </div>

    </div>

  </div>
</a>
