<div class="ly--form-item">
  <label for="time-picker-1" class="ly--label">Select a time</label>
  <div class="ly--time-picker">
    <div class="ly--time-picker__input">
      <input id="time-picker-1" type="text" class="ly--time-picker__input-field" pattern="(1[012]|[1-9]):[0-5][0-9](\\s)?(?i)"
        placeholder="hh:mm" maxlength="5" />
      <div class="ly--form-requirement">
        Invalid time.
      </div>
    </div>
    <div class="ly--time-picker__select ly--select ly--select--inline">
      <label for="select-id-1" class="ly--label ly--visually-hidden">Select AM/PM</label>
      <select id="select-id-1" class="ly--select-input">
        <option class="ly--select-option" value="AM">AM</option>
        <option class="ly--select-option" value="PM">PM</option>
      </select>
      <svg class="ly--select__arrow" width="10" height="5" viewBox="0 0 10 5" fill-rule="evenodd">
        <path d="M10 0L5 5 0 0z"></path>
      </svg>
    </div>
    <div class="ly--time-picker__select ly--select ly--select--inline">
      <label for="select-id-2" class="ly--label ly--visually-hidden">Select timezone</label>
      <select id="select-id-2" class="ly--select-input">
        <option class="ly--select-option" value="option-1">Timezone 1</option>
        <option class="ly--select-option" value="option-2">Timezone 2</option>
        <option class="ly--select-option" value="option-3">Timezone 3</option>
      </select>
      <svg class="ly--select__arrow" width="10" height="5" viewBox="0 0 10 5" fill-rule="evenodd">
        <path d="M10 0L5 5 0 0z"></path>
      </svg>
    </div>
  </div>
</div>
