<div class="ly--form-item ly--multi-select ly--list-box">
  <div role="button" class="ly--list-box__field" tabindex="0" aria-label="open menu" aria-expanded="false" aria-haspopup="true">
    <span class="ly--list-box__label">Label</span>
    <div class="ly--list-box__menu-icon">
      <svg fill-rule="evenodd" height="5" name="caret--down" role="img" viewBox="0 0 10 5" width="10" aria-label="Open menu">
        <title>Open menu</title>
        <path d="M10 0L5 5 0 0z"></path>
      </svg>
    </div>
  </div>
</div>
<div class="ly--form-item ly--multi-select ly--list-box">
  <div role="button" class="ly--list-box__field" tabindex="0" aria-label="close menu" aria-expanded="true" aria-haspopup="true">
    <span class="ly--list-box__label">Label</span>
    <div class="ly--list-box__menu-icon ly--list-box__menu-icon--open">
      <svg fill-rule="evenodd" height="5" name="caret--down" role="img" viewBox="0 0 10 5" width="10" aria-label="Close menu">
        <title>Close menu</title>
        <path d="M10 0L5 5 0 0z"></path>
      </svg>
    </div>
  </div>
  <div class="ly--list-box__menu">
    <div class="ly--list-box__menu-item" id="downshift-1-item-0">
      <div class="ly--form-item ly--checkbox-wrapper">
        <label for="downshift-1-item-0" class="ly--checkbox-label">
          <input type="checkbox" name="Option 1" readonly="" tabindex="-1" class="ly--checkbox" id="downshift-1-item-0" value="on">
          <span class="ly--checkbox-appearance">
            <svg class="ly--checkbox-checkmark" fill-rule="evenodd" height="9" name="checkmark" role="img" viewBox="0 0 12 9" width="12" aria-label="Select this item">
              <title>Select this item</title>
              <path d="M4.1 6.1L1.4 3.4 0 4.9 4.1 9l7.6-7.6L10.3 0z"></path>
            </svg>
          </span>
          <span class="ly--checkbox-label-text">Option 1</span>
        </label>
      </div>
    </div>
    <div class="ly--list-box__menu-item" id="downshift-1-item-1">
      <div class="ly--form-item ly--checkbox-wrapper">
        <label for="downshift-1-item-1" class="ly--checkbox-label">
          <input type="checkbox" name="Option 2" readonly="" tabindex="-1" class="ly--checkbox" id="downshift-1-item-1" value="on">
          <span class="ly--checkbox-appearance">
            <svg class="ly--checkbox-checkmark" fill-rule="evenodd" height="9" name="checkmark" role="img" viewBox="0 0 12 9" width="12" aria-label="Select this item">
              <title>Select this item</title>
              <path d="M4.1 6.1L1.4 3.4 0 4.9 4.1 9l7.6-7.6L10.3 0z"></path>
            </svg>
          </span>
          <span class="ly--checkbox-label-text">Option 2</span>
        </label>
      </div>
    </div>
    <div class="ly--list-box__menu-item" id="downshift-1-item-2">
      <div class="ly--form-item ly--checkbox-wrapper">
        <label for="downshift-1-item-2" class="ly--checkbox-label">
          <input type="checkbox" name="Option 3" readonly="" tabindex="-1" class="ly--checkbox" id="downshift-1-item-2" value="on">
          <span class="ly--checkbox-appearance">
            <svg class="ly--checkbox-checkmark" fill-rule="evenodd" height="9" name="checkmark" role="img" viewBox="0 0 12 9" width="12" aria-label="Select this item">
              <title>Select this item</title>
              <path d="M4.1 6.1L1.4 3.4 0 4.9 4.1 9l7.6-7.6L10.3 0z"></path>
            </svg>
          </span>
          <span class="ly--checkbox-label-text">Option 3</span>
        </label>
      </div>
    </div>
    <div class="ly--list-box__menu-item" id="downshift-1-item-3">
      <div class="ly--form-item ly--checkbox-wrapper">
        <label for="downshift-1-item-3" class="ly--checkbox-label">
          <input type="checkbox" name="Option 4" readonly="" tabindex="-1" class="ly--checkbox" id="downshift-1-item-3" value="on">
          <span class="ly--checkbox-appearance">
            <svg class="ly--checkbox-checkmark" fill-rule="evenodd" height="9" name="checkmark" role="img" viewBox="0 0 12 9" width="12" aria-label="Select this item">
              <title>Select this item</title>
              <path d="M4.1 6.1L1.4 3.4 0 4.9 4.1 9l7.6-7.6L10.3 0z"></path>
            </svg>
          </span>
          <span class="ly--checkbox-label-text">Option 4</span>
        </label>
      </div>
    </div>
  </div>
</div>
