<fieldset class="ly--fieldset">
  <legend class="ly--label">Checkbox (input + label)</legend>
  <!-- input + label -->
  <div class="ly--form-item ly--checkbox-wrapper">
    <input id="ly--checkbox-new" class="ly--checkbox" type="checkbox" value="new" name="checkbox" checked>
    <label for="ly--checkbox-new" class="ly--checkbox-label">Checkbox</label>
  </div>
  <!-- input + label disabled -->
  <div class="ly--form-item ly--checkbox-wrapper">
    <input id="ly--checkbox-disabled" class="ly--checkbox" type="checkbox" value="new" name="checkbox" disabled>
    <label for="ly--checkbox-disabled" class="ly--checkbox-label">Disabled checkbox</label>
  </div>
  <!-- input + label indeterminate -->
  <div class="ly--form-item ly--checkbox-wrapper">
    <input id="ly--checkbox-ind" class="ly--checkbox" type="checkbox" value="new" name="checkbox" aria-checked="mixed">
    <label for="ly--checkbox-ind" class="ly--checkbox-label">Indeterminate checkbox</label>
  </div>
</fieldset>
<fieldset class="ly--fieldset">
  <legend class="ly--label">Checkbox (input > label)</legend>
    <!-- label > input -->
    <div class="ly--form-item ly--checkbox-wrapper">
      <label for="ly--checkbox-new2" class="ly--checkbox-label">
        <input id="ly--checkbox-new2" class="ly--checkbox" type="checkbox" value="yellow" name="checkbox" checked>
        Checkbox
      </label>
    </div>
    <!-- label > input -->
    <div class="ly--form-item ly--checkbox-wrapper">
      <label for="ly--checkbox-new2" class="ly--checkbox-label">
        <input id="ly--checkbox-new2" class="ly--checkbox" type="checkbox" value="yellow" name="checkbox" disabled>
        Disabled checkbox
      </label>
    </div>
    <!-- label > input -->
    <div class="ly--form-item ly--checkbox-wrapper">
      <label for="ly--checkbox-ind2" class="ly--checkbox-label" data-contained-checkbox-state="mixed">
        <input id="ly--checkbox-ind2" class="ly--checkbox" type="checkbox" value="yellow" name="checkbox" aria-checked="mixed">
        Indeterminate checkbox
      </label>
    </div>
</fieldset>