<div data-tile="expandable" class="ly--tile ly--tile--expandable" tabindex="0">
  <button class="ly--tile__chevron">
    <svg width="12" height="8" viewBox="0 0 12 8" fill-rule="evenodd">
      <path d="M10.6 0L6 4.7 1.4 0 0 1.4l6 6.1 6-6.1z"></path>
    </svg>
  </button>
  <div class="ly--tile-content">
    <span data-tile-atf class="ly--tile-content__above-the-fold">
      <!-- Above the fold content here -->
    </span>
    <span class="ly--tile-content__below-the-fold">
      <!-- Rest of the content here -->
    </span>
  </div>
</div>
