<div class="ly--form-item">
  <label for="select-id" class="ly--label">Select label</label>
  <div class="ly--select">
    <select id="select-id" class="ly--select-input">
      <option class="ly--select-option" disabled selected hidden>Choose an option</option>
      <option class="ly--select-option" value="solong">A much longer option that is worth having around to check how text flows</option>
      <optgroup class="ly--select-optgroup" label="Category 1">
        <option class="ly--select-option" value="option1">Option 1</option>
        <option class="ly--select-option" value="option2">Option 2</option>
      </optgroup>
      <optgroup class="ly--select-optgroup" label="Category 2">
        <option class="ly--select-option" value="option1">Option 1</option>
        <option class="ly--select-option" value="option2">Option 2</option>
      </optgroup>
    </select>
    <svg class="ly--select__arrow" width="10" height="5" viewBox="0 0 10 5" fill-rule="evenodd">
      <path d="M10 0L5 5 0 0z"></path>
    </svg>
  </div>
</div>
