

<?php if ( is_front_page() ):?>
  <div class="bx--navbar--submenu transparent">
<?php else: ?>
  <div class="bx--navbar--submenu">
<?php endif;?>

  <div class="snippet"></div>

  <!-- Navbar menu -->
  <?php if( have_rows('submenu_services', 'option') ):?>
      <div class="submenu--container submenu-1">
        <div class="submenu--heading-container">
          <h5 class="bx--type-zeta__subheading">Våra tjänster</h5>
        </div>

        <div class="submenu--card-container">

      <?php while( have_rows('submenu_services', 'option') ): the_row();

          // vars
          $img = get_sub_field('image', 'option');
          $link = get_sub_field('link', 'option');
          $text = $link['title'];
          $cardlink = $link['url'];
          $label = get_sub_field('link_animation', 'option');

          if( $link ):?>

          <a class="card-link" href="<?= $cardlink ?>">
              <div class="card card-service__sm">

                <?php if( $img ): ?>
                  <div class="service-img-container">
                      <img src="<?= $img ?>" class="service-img" alt="" />
                  </div>
                  <?php endif; ?>

                <div class="service-text-container">
                  <p><?= $text ?></p>
                </div>


              </div>
          	</a>


          <?php endif; ?>

      <?php endwhile; ?>

      </div>
      <div class="submenu--footer">
        <p class="paragraph no-margin">Dags att ta första steget på er digitala tillväxtresa,</p>
        <a href="/tjanster/tillvaxtanalys" class="bx--link">tillväxtanalysen</a>
      </div>

    </div>

  <?php endif; ?>

  <!-- Navbar menu -->
  <?php if( have_rows('submenu_consultants', 'option') ):?>
      <div class="submenu--container submenu-2">
        <div class="submenu--heading-container">
          <h5 class="bx--type-zeta__subheading">Våra konsultroller</h5>
        </div>

        <div class="submenu--card-container">

      <?php while( have_rows('submenu_consultants', 'option') ): the_row();

          // vars
          $img = get_sub_field('image', 'option');
          $link = get_sub_field('link', 'option');
          $text = $link['title'];
          $cardlink = $link['url'];
          $label = get_sub_field('link_animation', 'option');

          if( $link ):?>

          <a class="card-link" href="<?= $cardlink ?>">
            <div class="card card-consultant__sm">
              <div class="consultants-text-container">
                <p class="paragraph no-margin consultants-heading"><?= $text ?></p>
              </div>

            </div>
          </a>


          <?php endif; ?>

      <?php endwhile; ?>

      <div class="submenu--footer">
        <p class="paragraph no-margin">Dags att ta första steget på er digitala tillväxtresa,</p>
        <a href="/tjanster/tillvaxtanalys" class="bx--link">tillväxtanalysen</a>
      </div>

      </div>

    </div>

  <?php endif; ?>

</div>
