<div class="ly--navbar--submenu__mobile">

  <!-- Navbar menu -->
  <?php if( have_rows('navbar_menu_mobile', 'option') ): ?>

      <ul class="navbar--ul">

      <?php while( have_rows('navbar_menu_mobile', 'option') ): the_row(); ?>

        <li class="navbar--li">

          <?php
          // vars
          $link = get_sub_field('menu_link', 'option');
          $label = get_sub_field('link_animation', 'option');

          if( $link ):?>

            <a class=" ly--type-beta navbar--submenu__text" href="<?= $link['url']; ?>" target="<?= $link['target']; ?>">
              <?= $link['title']; ?>
              <?php if ( $label):?><span class="link--label"></span><?php endif;?>
            </a>

          <?php endif; ?>

        </li>

      <?php endwhile; ?>

      </ul>

  <?php endif; ?>

</div>
