<div class="submenu submenu--why-peakon submenu--left" id="submenu">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div class="submenu__indicator"></div>
      </div>
    </div>
  </div>

  <div class="submenu__sections">
    <section class="submenu__section submenu__section--product">
  <div class="submenu__content">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <h4 class="preheading-small submenu__title">
            Engage Product Features          </h4>
        </div>
      </div>
      <div class="row submenu__items">
        <div class="col-sm-12">
          <div class="submenu__features-container">
              <div class="submenu__feature">
                <a href="https://peakon.com/products/engage/manager-dashboard/" class="submenu-item">
                  <div class="submenu-item__title l-flex">
                    <div class="submenu-item__icon">
                      <svg class="icon icon-dashboard-green" aria-hidden="true" role="img"> <use href="#dashboard-green" xlink:href="#dashboard-green"></use> </svg>
                    </div>
                    <div class="submenu-item__label">
                      Manager Dashboards
                     </div>
                  </div>
                  <div class="submenu-item__text">
                    Empower your managers to drive change
                  </div>
                </a>

              </div>
                          <div class="submenu__feature">
                <a href="https://peakon.com/products/engage/bespoke-benchmarking/" class="submenu-item">
                  <div class="submenu-item__title l-flex">
                    <div class="submenu-item__icon">
                      <svg class="icon icon-benchmarking-green" aria-hidden="true" role="img"> <use href="#benchmarking-green" xlink:href="#benchmarking-green"></use> </svg>                    </div>
                    <div class="submenu-item__label">
                      Bespoke Benchmarking                    </div>
                  </div>
                  <div class="submenu-item__text">
                    Better benchmarks to measure performance                  </div>
                </a>
              </div>
                          <div class="submenu__feature">
                <a href="https://peakon.com/products/engage/employee-conversations/" class="submenu-item">
                  <div class="submenu-item__title l-flex">
                    <div class="submenu-item__icon">
                      <svg class="icon icon-1-to-1-green" aria-hidden="true" role="img"> <use href="#1-to-1-green" xlink:href="#1-to-1-green"></use> </svg>                    </div>
                    <div class="submenu-item__label">
                      Employee Conversations                    </div>
                  </div>
                  <div class="submenu-item__text">
                    Involve everyone in the engagement process                  </div>
                </a>
              </div>
                          <div class="submenu__feature">
                <a href="https://peakon.com/products/engage/intelligent-question-assignment/" class="submenu-item">
                  <div class="submenu-item__title l-flex">
                    <div class="submenu-item__icon">
                      <svg class="icon icon-sampling-green" aria-hidden="true" role="img"> <use href="#sampling-green" xlink:href="#sampling-green"></use> </svg>                    </div>
                    <div class="submenu-item__label">
                      Intelligent Question Assignment                    </div>
                  </div>
                  <div class="submenu-item__text">
                    Reduce survey fatigue and improve insight                  </div>
                </a>
              </div>
                          <div class="submenu__feature">
                <a href="https://peakon.com/products/engage/security/" class="submenu-item">
                  <div class="submenu-item__title l-flex">
                    <div class="submenu-item__icon">
                      <svg class="icon icon-security-green" aria-hidden="true" role="img"> <use href="#security-green" xlink:href="#security-green"></use> </svg>                    </div>
                    <div class="submenu-item__label">
                      Security                    </div>
                  </div>
                  <div class="submenu-item__text">
                    Industry-leading data protection and security                  </div>
                </a>
              </div>
                          <div class="submenu__feature">
                <a href="https://peakon.com/products/engage/universal-accessibility/" class="submenu-item">
                  <div class="submenu-item__title l-flex">
                    <div class="submenu-item__icon">
                      <svg class="icon icon-language-green" aria-hidden="true" role="img"> <use href="#language-green" xlink:href="#language-green"></use> </svg>                    </div>
                    <div class="submenu-item__label">
                      Universal Accessibility                    </div>
                  </div>
                  <div class="submenu-item__text">
                    Ensure every employee voice is heard                  </div>
                </a>
              </div>
                          <div class="submenu__feature">
                <a href="https://peakon.com/products/engage/values/" class="submenu-item">
                  <div class="submenu-item__title l-flex">
                    <div class="submenu-item__icon">
                      <svg class="icon icon-values-green" aria-hidden="true" role="img"> <use href="#values-green" xlink:href="#values-green"></use> </svg>                    </div>
                    <div class="submenu-item__label">
                      Values                    </div>
                  </div>
                  <div class="submenu-item__text">
                    Promote the right behaviours                  </div>
                </a>
              </div>
                          <div class="submenu__feature">
                <a href="https://peakon.com/products/engage/actions/" class="submenu-item">
                  <div class="submenu-item__title l-flex">
                    <div class="submenu-item__icon">
                      <svg class="icon icon-actions-green" aria-hidden="true" role="img"> <use href="#actions-green" xlink:href="#actions-green"></use> </svg>                    </div>
                    <div class="submenu-item__label">
                      Actions                    </div>
                  </div>
                  <div class="submenu-item__text">
                    Easy and effective action planning                  </div>
                </a>
              </div>
                          <div class="submenu__feature">
                <a href="https://peakon.com/products/engage/enterprise-ready/" class="submenu-item">
                  <div class="submenu-item__title l-flex">
                    <div class="submenu-item__icon">
                      <svg class="icon icon-structure-green" aria-hidden="true" role="img"> <use href="#structure-green" xlink:href="#structure-green"></use> </svg>                    </div>
                    <div class="submenu-item__label">
                      Enterprise Ready                    </div>
                  </div>
                  <div class="submenu-item__text">
                    Flexibility, scale &amp; access control                  </div>
                </a>
              </div>
                          <div class="submenu__feature">
                <a href="https://peakon.com/products/engage/integrations/" class="submenu-item">
                  <div class="submenu-item__title l-flex">
                    <div class="submenu-item__icon">
                      <svg class="icon icon-integrations-green" aria-hidden="true" role="img"> <use href="#integrations-green" xlink:href="#integrations-green"></use> </svg>                    </div>
                    <div class="submenu-item__label">
                      Integrations                    </div>
                  </div>
                  <div class="submenu-item__text">
                    Seamless cross-platform experiences                  </div>
                </a>
              </div>
                          <div class="submenu__feature">
                <a href="https://peakon.com/products/engage/instant-results/" class="submenu-item">
                  <div class="submenu-item__title l-flex">
                    <div class="submenu-item__icon">
                      <svg class="icon icon-real-time-green" aria-hidden="true" role="img"> <use href="#real-time-green" xlink:href="#real-time-green"></use> </svg>                    </div>
                    <div class="submenu-item__label">
                      Instant Results                    </div>
                  </div>
                  <div class="submenu-item__text">
                    Minimum time, maximum value                  </div>
                </a>
              </div>
                          <div class="submenu__feature">
                <a href="https://peakon.com/products/engage/topic-and-text-analysis/" class="submenu-item">
                  <div class="submenu-item__title l-flex">
                    <div class="submenu-item__icon">
                      <svg class="icon icon-topics-green" aria-hidden="true" role="img"> <use href="#topics-green" xlink:href="#topics-green"></use> </svg>                    </div>
                    <div class="submenu-item__label">
                      Topic &amp; Text Analysis                    </div>
                  </div>
                  <div class="submenu-item__text">
                    Powerful insight from employee comments                  </div>
                </a>
              </div>
                      </div>
        </div>
      </div>
    </div>
  </div>
  <div class="submenu__footer">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <div class="submenu__banner l-flex">
            <h3 class="heading-3 color-green">
              Blog:            </h3>
            <p class="p-small submenu__post-title">
              Read our latest product announcements            </p>
            <a href="https://peakon.com/blog/tag/product-news/" class="underline-link">
              <span class="underline-link__label">
                Learn more              </span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
    <section class="submenu__section submenu__section--why-peakon">
  <div class="submenu__content">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <h4 class="preheading-small submenu__title">
            Select your industry            <small>Discover how Peakon can help you</small>
          </h4>
        </div>
      </div>
      <div class="row submenu__items">
        <div class="col-md-4">
          <a href="https://peakon.com/why-peakon/financial-services/" class="submenu-item submenu-item--industry">
            <div class="submenu-item__icon">
              <svg class="icon icon-financial-green" aria-hidden="true" role="img"> <use href="#financial-green" xlink:href="#financial-green"></use> </svg>            </div>
            <div class="submenu-item__label-container">
              <div class="submenu-item__label">
                Financial Services              </div>
              <div class="submenu-item__text">
                Stay ahead of the competition              </div>
            </div>
          </a>
          <a href="https://peakon.com/why-peakon/manufacturing-construction/" class="submenu-item submenu-item--industry">
            <div class="submenu-item__icon">
              <svg class="icon icon-manufacturing-green" aria-hidden="true" role="img"> <use href="#manufacturing-green" xlink:href="#manufacturing-green"></use> </svg>            </div>
            <div class="submenu-item__label-container">
              <div class="submenu-item__label">
                Manufacturing &amp; Construction              </div>
              <div class="submenu-item__text">
                Build a successful company culture              </div>
            </div>
          </a>
        </div>
        <div class="col-md-4">
          <a href="https://peakon.com/why-peakon/technology-startups/" class="submenu-item submenu-item--industry">
            <div class="submenu-item__icon">
              <svg class="icon icon-technology-green" aria-hidden="true" role="img"> <use href="#technology-green" xlink:href="#technology-green"></use> </svg>            </div>
            <div class="submenu-item__label-container">
              <div class="submenu-item__label">
                Technology &amp; Startups              </div>
              <div class="submenu-item__text">
                Drive innovation through your people              </div>
            </div>
          </a>
          <a href="https://peakon.com/why-peakon/retail-hospitality/" class="submenu-item submenu-item--industry">
            <div class="submenu-item__icon">
              <svg class="icon icon-retail-green" aria-hidden="true" role="img"> <use href="#retail-green" xlink:href="#retail-green"></use> </svg>            </div>
            <div class="submenu-item__label-container">
              <div class="submenu-item__label">
                Retail &amp; Hospitality              </div>
              <div class="submenu-item__text">
                Discover the secret to great service              </div>
            </div>
          </a>
        </div>
        <div class="col-md-4">
          <a href="https://peakon.com/why-peakon/professional-services/" class="submenu-item submenu-item--industry">
            <div class="submenu-item__icon">
              <svg class="icon icon-professional-green" aria-hidden="true" role="img"> <use href="#professional-green" xlink:href="#professional-green"></use> </svg>            </div>
            <div class="submenu-item__label-container">
              <div class="submenu-item__label">
                Professional Services              </div>
              <div class="submenu-item__text">
                Increase performance through engagement              </div>
            </div>
          </a>
          <a href="https://peakon.com/why-peakon/charity-non-profit/" class="submenu-item submenu-item--industry">
            <div class="submenu-item__icon">
              <svg class="icon icon-charity-green" aria-hidden="true" role="img"> <use href="#charity-green" xlink:href="#charity-green"></use> </svg>            </div>
            <div class="submenu-item__label-container">
              <div class="submenu-item__label l-flex">
                Charity &amp; Non-Profit              </div>
              <div class="submenu-item__text">
                Help your employees make a difference              </div>
            </div>
          </a>
        </div>
        <div class="col-md-4">
          <a href="https://peakon.com/why-peakon/government-public-sector/" class="submenu-item submenu-item--industry">
            <div class="submenu-item__icon">
              <svg class="icon icon-government-green" aria-hidden="true" role="img"> <use href="#government-green" xlink:href="#government-green"></use> </svg>            </div>
            <div class="submenu-item__label-container">
              <div class="submenu-item__label l-flex">
                Government &amp; Public Sector              </div>
              <div class="submenu-item__text">
                Support your people and drive change              </div>
            </div>
          </a>
        </div>
      </div>
    </div>
  </div>
  <div class="submenu__footer">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <div class="submenu__banner l-flex">
            <h3 class="heading-3 color-green">
              Blog:            </h3>
            <p class="p-small submenu__post-title">
              Why You Need an Updated Approach to Diversity and Inclusion            </p>
            <a href="https://peakon.com/blog/future-work/diversity-and-inclusion/" class="underline-link">
              <span class="underline-link__label">
                Learn more              </span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
    <section class="submenu__section submenu__section--resources">
  <div class="submenu__content">
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <h4 class="preheading-small submenu__title">
            Resources          </h4>

          <div class="row submenu__items">
                                                      <div class="col-md-6">
                <a href="https://peakon.com/resources/customer-stories/" class="submenu-item submenu-item--industry">
                  <div class="submenu-item__icon">
                  <svg class="icon icon-customer-stories" aria-hidden="true" role="img"> <use href="#customer-stories" xlink:href="#customer-stories"></use> </svg>                  </div>
                  <div class="submenu-item__label-container">
                    <div class="submenu-item__label">
                      Customer Stories                    </div>
                    <div class="submenu-item__text">
                      See how our customers are using Peakon                    </div>
                  </div>
                </a>
              </div>
                                                      <div class="col-md-6">
                <a href="https://peakon.com/resources/guides/" class="submenu-item submenu-item--industry">
                  <div class="submenu-item__icon">
                  <svg class="icon icon-guides" aria-hidden="true" role="img"> <use href="#guides" xlink:href="#guides"></use> </svg>                  </div>
                  <div class="submenu-item__label-container">
                    <div class="submenu-item__label">
                      Guides                    </div>
                    <div class="submenu-item__text">
                      Learn and grow with Peakon guides                    </div>
                  </div>
                </a>
              </div>
                                                        <div class="clearfix hidden-sm"></div>
                            <div class="col-md-6">
                <a href="https://peakon.com/resources/webinars/" class="submenu-item submenu-item--industry">
                  <div class="submenu-item__icon">
                  <svg class="icon icon-webinars" aria-hidden="true" role="img"> <use href="#webinars" xlink:href="#webinars"></use> </svg>                  </div>
                  <div class="submenu-item__label-container">
                    <div class="submenu-item__label">
                      Webinars                    </div>
                    <div class="submenu-item__text">
                      Online events hosted by our team                     </div>
                  </div>
                </a>
              </div>
                      </div>
        </div>
        <div class="col-md-4 submenu__aside">
          <h4 class="preheading-small submenu__title">
            Other          </h4>

          <div class="submenu__items">
            <a href="https://help.peakon.com" target="_blank" rel="noopener noreferrer" class="submenu-item submenu-item--industry">
              <div class="submenu-item__icon">
                <svg class="icon icon-help-center-green" aria-hidden="true" role="img"> <use href="#help-center-green" xlink:href="#help-center-green"></use> </svg>              </div>
              <div class="submenu-item__label-container">
                <div class="submenu-item__label">
                  Help Centre                </div>
                <div class="submenu-item__text">
                  Learn how to install, configure, and use Peakon                </div>
              </div>
            </a>
            <a href="https://peakon.com/events/" class="submenu-item submenu-item--industry">
              <div class="submenu-item__icon">
                <svg class="icon icon-events-green" aria-hidden="true" role="img"> <use href="#events-green" xlink:href="#events-green"></use> </svg>              </div>
              <div class="submenu-item__label-container">
                <div class="submenu-item__label">
                  Events                </div>
                <div class="submenu-item__text">
                  Come meet us in person                </div>
              </div>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
  </div>
</div>
