<?php if( have_rows('our_offer') ):

	while( have_rows('our_offer') ): the_row();

		// vars
		$subheading = get_sub_field('subheading');
		$heading = get_sub_field('heading');

    $icon1 = get_sub_field('icon_one');
    $heading1 = get_sub_field('heading_one');
    $paragraph1 = get_sub_field('paragraph_one');

		?>

    <div class="bx--grid our-offer section-6rem">
      <div class="bx--row">

        <div class="bx--col-lg-12 section-heading">
          <h5 class="bx--type-delta__subheading"><?= $subheading ?></h5>
          <h2 class="bx--type-alpha"><?= $heading ?></h2>
        </div>

        <?php if( have_rows('our_offer_icons') ): ?>

      	<?php while( have_rows('our_offer_icons') ): the_row();

      		// vars
      		$icon = get_sub_field('icon');
      		$heading = get_sub_field('heading');
      		$paragraph = get_sub_field('paragraph');

      		?>

          <div class="bx--col-lg-4 bx--col-md-6 bx--col-sm-12 our-offer--col">

            <div class="our-offer--icon-container">
              <img src="<?= $icon ?>" class="our-offer--icon-container__icon"/>
            </div>
            <div class="our-offer--text-container">
              <h5 class="bx--type-delta__subheading"><?= $heading ?></h5>
              <p><?= $paragraph ?></p>
            </div>

          </div>

      	<?php endwhile; ?>

      <?php endif; ?>


      </div>

    </div>


	<?php endwhile; ?>

<?php endif; ?>
