<div class="ly--form-item">
  <input class="ly--toggle" id="toggle1" type="checkbox">
  <label class="ly--toggle__label" for="toggle1">
    <span class="ly--toggle__text--left">Off</span>
    <span class="ly--toggle__appearance"></span>
    <span class="ly--toggle__text--right">On</span>
  </label>
</div>

<fieldset class="ly--fieldset">
  <legend class="ly--label">Toggle w/ Label</legend>
  <div class="ly--form-item">
    <input class="ly--toggle" id="toggle2" type="checkbox">
    <label class="ly--toggle__label" for="toggle2">
    <span class="ly--toggle__text--left">Off</span>
    <span class="ly--toggle__appearance"></span>
    <span class="ly--toggle__text--right">On</span>
  </label>
  </div>
</fieldset>

<div class="ly--form-item">
  <input class="ly--toggle" id="toggle3" type="checkbox" disabled>
  <label class="ly--toggle__label" for="toggle3">
    <span class="ly--toggle__text--left">Off</span>
    <span class="ly--toggle__appearance"></span>
    <span class="ly--toggle__text--right">On</span>
  </label>
</div>

<li class="tg-list-item">
  <h4>iOS</h4>
  <input class="toggle toggle-ios" id="cb2" type="checkbox"/>
  <label class="toggle-btn" for="cb2"></label>
</li>
