<div class="ly--form-item">
  <input class="ly--toggle ly--toggle--small" id="toggle4" type="checkbox" aria-label="Label Name">
  <label class="ly--toggle__label" for="toggle4">
    <span class="ly--toggle__appearance">
      <svg class="ly--toggle__check" width="6px" height="5px" viewBox="0 0 6 5">
        <path d="M2.2 2.7L5 0 6 1 2.2 5 0 2.7 1 1.5z"/>
      </svg>
    </span>
  </label>
</div>

<div class="ly--form-item">
  <input class="ly--toggle ly--toggle--small" id="toggle5" type="checkbox" aria-label="Label Name" disabled>
  <label class="ly--toggle__label" for="toggle5"> 
    <span class="ly--toggle__appearance">
      <svg class="ly--toggle__check" width="6px" height="5px" viewBox="0 0 6 5">
        <path d="M2.2 2.7L5 0 6 1 2.2 5 0 2.7 1 1.5z"/>
      </svg>
    </span>
  </label>
</div>
