<div class="ly--responsive-table-container" data-responsive-table>
  <table class="ly--responsive-table ly--responsive-table--static-size" data-table>
    <thead class="ly--table-head">
      <tr class="ly--table-row">
        <th tabindex="0" class="ly--table-header ly--table-sort" data-event="sort">
          <span>First Name</span>
          <svg class="ly--table-sort__svg" width="10" height="5" viewBox="0 0 10 5" fill-rule="evenodd">
            <path d="M10 0L5 5 0 0z"></path>
          </svg>
        </th>
        <th tabindex="0" class="ly--table-header ly--table-sort" data-event="sort">
          <span>Last Name</span>
          <svg class="ly--table-sort__svg" width="10" height="5" viewBox="0 0 10 5" fill-rule="evenodd">
            <path d="M10 0L5 5 0 0z"></path>
          </svg>
        </th>
        <th tabindex="0" class="ly--table-header ly--table-sort" data-event="sort">
          <span>House</span>
          <svg class="ly--table-sort__svg" width="10" height="5" viewBox="0 0 10 5" fill-rule="evenodd">
            <path d="M10 0L5 5 0 0z"></path>
          </svg>
        </th>
      </tr>
    </thead>
    <tbody class="ly--table-body">
      <tr tabindex="0" class="ly--table-row ly--parent-row" data-parent-row>
        <td>Harry</td>
        <td>Potter</td>
        <td>Gryffindor</td>
      </tr>
      <tr tabindex="0" class="ly--table-row ly--parent-row" data-parent-row>
        <td>Hermoine</td>
        <td>Granger</td>
        <td>Gryffindor</td>
      </tr>
      <tr tabindex="0" class="ly--table-row ly--parent-row" data-parent-row>
        <td>Ron</td>
        <td>Weasley</td>
        <td>Gryffindor</td>
      </tr>
      <tr tabindex="0" class="ly--table-row ly--parent-row" data-parent-row>
        <td>Draco</td>
        <td>Malfoy</td>
        <td>Slytherin</td>
      </tr>
      <tr tabindex="0" class="ly--table-row ly--parent-row" data-parent-row>
        <td>Blaise</td>
        <td>Zabini</td>
        <td>Slytherin</td>
      </tr>
      <tr tabindex="0" class="ly--table-row ly--parent-row" data-parent-row>
        <td>Cedric</td>
        <td>Diggory</td>
        <td>Hufflepuff</td>
      </tr>
      <tr tabindex="0" class="ly--table-row ly--parent-row" data-parent-row>
        <td>Luna</td>
        <td>Lovegood</td>
        <td>Ravenclaw</td>
      </tr>
      <tr tabindex="0" class="ly--table-row ly--parent-row" data-parent-row>
        <td>Cho</td>
        <td>Chang</td>
        <td>Ravenclaw</td>
      </tr>
    </tbody>
  </table>
</div>
