<button class="ly--btn ly--btn__primary" type="button" data-modal-target="#modal">Transactional</button>

<div data-modal id="modal" class="ly--modal" tabindex="-1">
  <div class="ly--modal-container">
    <div class="ly--modal-header">
      <p class="ly--modal-header__label ly--type-delta">Optional label</p>
      <p class="ly--modal-header__heading ly--type-beta">Modal heading</p>
      <button class="ly--modal-close" type="button" data-modal-close aria-label="close modal">
        <svg class="ly--modal-close__icon" width="10" height="10" viewBox="0 0 10 10" fill-rule="evenodd">
           <title>Close Modal</title>
          <path d="M9.8 8.6L8.4 10 5 6.4 1.4 10 0 8.6 3.6 5 .1 1.4 1.5 0 5 3.6 8.6 0 10 1.4 6.4 5z"></path>
        </svg>
      </button>
    </div>

    <div class="ly--modal-content">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean id accumsan augue. Phasellus consequat augue vitae tellus tincidunt posuere. Curabitur justo urna, consectetur vel elit iaculis, ultrices condimentum risus. Nulla facilisi. Etiam venenatis molestie tellus. Quisque consectetur non risus eu rutrum. </p>
    </div>

    <div class="ly--modal-footer">
      <button class="ly--btn ly--btn--secondary" type="button" data-modal-close>Secondary button</button>
      <button class="ly--btn ly--btn__primary" type="button" data-modal-primary-focus>Primary button</button>
    </div>
  </div>
</div>

<button class="ly--btn ly--btn--danger--primary" type="button" data-modal-target="#modal--danger">Transactional Danger</button>

<div data-modal id="modal--danger" class="ly--modal ly--modal--danger" tabindex="-1">
  <div class="ly--modal-container">
    <div class="ly--modal-header">
      <p class="ly--modal-header__label ly--type-delta">Optional label</p>
      <p class="ly--modal-header__heading ly--type-beta">Modal heading</p>
      <button class="ly--modal-close" type="button" data-modal-close aria-label="close modal">
        <svg class="ly--modal-close__icon" width="10" height="10" viewBox="0 0 10 10" fill-rule="evenodd">
           <title>Close Modal</title>
          <path d="M9.8 8.6L8.4 10 5 6.4 1.4 10 0 8.6 3.6 5 .1 1.4 1.5 0 5 3.6 8.6 0 10 1.4 6.4 5z"></path>
        </svg>
      </button>
    </div>

    <div class="ly--modal-content">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean id accumsan augue. Phasellus consequat augue vitae tellus tincidunt posuere. Curabitur justo urna, consectetur vel elit iaculis, ultrices condimentum risus. Nulla facilisi. Etiam venenatis molestie tellus. Quisque consectetur non risus eu rutrum. </p>
    </div>

    <div class="ly--modal-footer">
      <button class="ly--btn ly--btn--tertiary" type="button" data-modal-close>Tertiary button</button>
      <button class="ly--btn ly--btn--danger--primary" type="button" data-modal-primary-focus>Danger button</button>
    </div>
  </div>
</div>
