<div data-notification class="ly--toast-notification ly--toast-notification--error" role="alert">
  <div class="ly--toast-notification__details">
    <h3 class="ly--toast-notification__title">Notification title</h3>
    <p class="ly--toast-notification__subtitle">Subtitle text goes here.</p>
    <p class="ly--toast-notification__caption">Time stamp [00:00:00]</p>
  </div>
  <button data-notification-btn class="ly--toast-notification__close-button" type="button">
    <svg class="ly--toast-notification__icon" aria-label="close" width="10" height="10" viewBox="0 0 10 10" fill-rule="evenodd">
      <path d="M9.8 8.6L8.4 10 5 6.4 1.4 10 0 8.6 3.6 5 .1 1.4 1.5 0 5 3.6 8.6 0 10 1.4 6.4 5z"></path>
    </svg>
  </button>
</div>

<div data-notification class="ly--toast-notification ly--toast-notification--info" aria-live="polite">
  <div class="ly--toast-notification__details">
    <h3 class="ly--toast-notification__title">Notification title</h3>
    <p class="ly--toast-notification__subtitle">Subtitle text goes here.</p>
    <p class="ly--toast-notification__caption">Time stamp [00:00:00]</p>
  </div>
  <button data-notification-btn class="ly--toast-notification__close-button" type="button">
    <svg class="ly--toast-notification__icon" aria-label="close" width="10" height="10" viewBox="0 0 10 10" fill-rule="evenodd">
      <path d="M9.8 8.6L8.4 10 5 6.4 1.4 10 0 8.6 3.6 5 .1 1.4 1.5 0 5 3.6 8.6 0 10 1.4 6.4 5z"></path>
    </svg>
  </button>
</div>

<div data-notification class="ly--toast-notification ly--toast-notification--success" aria-live="polite">
  <div class="ly--toast-notification__details">
    <h3 class="ly--toast-notification__title">Notification title</h3>
    <p class="ly--toast-notification__subtitle">Subtitle text goes here.</p>
    <p class="ly--toast-notification__caption">Time stamp [00:00:00]</p>
  </div>
  <button data-notification-btn class="ly--toast-notification__close-button" type="button">
    <svg class="ly--toast-notification__icon" aria-label="close" width="10" height="10" viewBox="0 0 10 10" fill-rule="evenodd">
      <path d="M9.8 8.6L8.4 10 5 6.4 1.4 10 0 8.6 3.6 5 .1 1.4 1.5 0 5 3.6 8.6 0 10 1.4 6.4 5z"></path>
    </svg>
  </button>
</div>

<div data-notification class="ly--toast-notification ly--toast-notification--warning" role="alert">
  <div class="ly--toast-notification__details">
    <h3 class="ly--toast-notification__title">Notification title</h3>
    <p class="ly--toast-notification__subtitle">Subtitle text goes here.</p>
    <p class="ly--toast-notification__caption">Time stamp [00:00:00]</p>
  </div>
  <button data-notification-btn class="ly--toast-notification__close-button" type="button">
    <svg class="ly--toast-notification__icon" aria-label="close" width="10" height="10" viewBox="0 0 10 10" fill-rule="evenodd">
      <path d="M9.8 8.6L8.4 10 5 6.4 1.4 10 0 8.6 3.6 5 .1 1.4 1.5 0 5 3.6 8.6 0 10 1.4 6.4 5z"></path>
    </svg>
  </button>
</div>
