<div class="ly--order-summary">
  <section class="ly--order-header">
    <p class="ly--order-header-title">Order Summary</p>
    <ul data-dropdown data-value class="ly--dropdown" tabindex="0">
      <li class="ly--dropdown-text">USD</li>
      <svg class="ly--dropdown__arrow" width="10" height="5" viewBox="0 0 10 5" fill-rule="evenodd">
        <path d="M10 0L5 5 0 0z"></path>
      </svg>
      <li>
        <ul class="ly--dropdown-list">
          <li data-option data-value="all" class="ly--dropdown-item"><a class="ly--dropdown-link" href="javascript:void(0)">USD</a></li>
          <li data-option data-value="cloudFoundry" class="ly--dropdown-item"><a class="ly--dropdown-link" href="javascript:void(0)">NOK</a></li>
          <li data-option data-value="staging" class="ly--dropdown-item"><a class="ly--dropdown-link" href="javascript:void(0)">GBP</a></li>
          <li data-option data-value="dea" class="ly--dropdown-item"><a class="ly--dropdown-link" href="javascript:void(0)">EUR</a></li>
        </ul>
      </li>
    </ul>

  </section>
  <ul class="ly--order-list">
    <li class="ly--order-category">
      <p class="ly--order-category-title">Category Label</p>
      <ul>
        <li class="ly--order-item">
          <p class="ly--order-detail">Detail one</p>
          <p class="ly--order-price">$10.00 /mo</p>
        </li>
        <li class="ly--order-item">
          <p class="ly--order-detail">Detail one</p>
          <p class="ly--order-price">$20.00</p>
        </li>
        <li class="ly--order-item">
          <p class="ly--order-detail">Detail one</p>
          <p class="ly--order-price">$20.00</p>
        </li>
      </ul>
    </li>
    <li class="ly--order-category">
      <p class="ly--order-category-title">Category Label</p>
      <ul>
        <li class="ly--order-item">
          <p class="ly--order-detail">Extra long detail to show what a long line is like</p>
          <p class="ly--order-price">$20000.00</p>
        </li>
        <li class="ly--order-item">
          <p class="ly--order-detail">Detail one</p>
          <p class="ly--order-price">$20.00</p>
        </li>
        <li class="ly--order-item">
          <p class="ly--order-detail">Detail one</p>
          <p class="ly--order-price">$20.00</p>
        </li>
      </ul>
    </li>
    <li class="ly--order-category">
      <p class="ly--order-category-title">Category Label</p>
      <ul>
        <li class="ly--order-item">
          <p class="ly--order-detail">Detail one</p>
          <p class="ly--order-price">$20.00</p>
        </li>
        <li class="ly--order-item">
          <p class="ly--order-detail">Detail one</p>
          <p class="ly--order-price">$20.00</p>
        </li>
        <li class="ly--order-item">
          <p class="ly--order-detail">Detail one</p>
          <p class="ly--order-price">$20.00</p>
        </li>
      </ul>
    </li>
  </ul>
  <section class="ly--order-total-container">
    <div class="ly--order-total">
      <p class="ly--order-total-text">Total due now</p>
      <p class="ly--order-total-price">
        $0.00
        <span>estimated</span>
      </p>
    </div>
    <p class="ly--order-total-subtitle"> * This is an estimated price based on a customer’s average usage, includes monthly and hourly pricing.</p>
    <button class="ly--btn ly--btn__primary" type="submit">Create Cluster</button>
    <button class="ly--btn ly--btn--secondary">Cancel</button>
  </section>
  <section class="ly--order-footer">
    <p class="ly--order-footer-text">Need Help?</p>
    &nbsp;
    <a href="" class="">Contact Bluemix Sales</a>
  </section>
</div>
