<nav class="ly--breadcrumb ly--breadcrumb--no-trailing-slash" aria-label="breadcrumb">
  <div class="ly--breadcrumb-item">
    <a href="#" class="ly--link">Breadcrumb 1</a>
  </div>
  <div class="ly--breadcrumb-item">
    <a href="#" class="ly--link">Breadcrumb 2</a>
  </div>
  <div class="ly--breadcrumb-item">
    <a href="#" class="ly--link">Breadcrumb 3</a>
  </div>
  <div class="ly--breadcrumb-item">
  </div>
</nav>
