<?php if( have_rows('country_section') ):?>

  <div class="countries">

    <?php while ( have_rows('country_section') ) : the_row();?>

      <div class="country">
          <img class="flag revealer-0" src="<?php the_sub_field('flag'); ?>"/>
          <h4 class="bx--type-epsilon revealer-100"><?php the_sub_field('phone'); ?></h4>
      </div>

    <?php endwhile;?>
    </div>
    <?php else :

              // no rows found

          endif;
    ?>
