<div class="contact-form">

  	<div class="bx--col-lg-12 bx--col-xs-12 contact-form--col">
    	<h3 class="contact-form--col__heading bx--type-beta"><?= $heading ?></h3>
    	<p class="contact-form--col__paragraph bx--type-delta__paragraph"><?= $paragraph ?></p>
  	</div>

  	<div class="bx--col-lg-6 bx--col-md-3 bx--col-xs-12 contact-form--col">
			<?php echo do_shortcode('[contact-form-7 id="1676" title="Contact form - Tuv Nord Case" html_class="bx--form-item"]'); ?>
    </div>

</div>
