
<?php if( have_rows('contact_form', 'option') ):

			while( have_rows('contact_form', 'option') ): the_row();

				// vars
				$heading = get_sub_field('heading','option');
		    $subheading = get_sub_field('subheading', 'option');
		?>

			<div class="bx--grid contact-form section-6rem">
			  <div class="bx--row">

			    	<div class="bx--col-lg-6 bx--col-xs-12 contact-form--col">
			      	<h3 class="bx--type-beta"><?= $heading ?></h3>
			      	<p class="bx--type-delta__paragraph"><?= $subheading ?></p>
			    	</div>

			    	<div class="bx--col-lg-6 bx--col-md-3 bx--col-xs-12 contact-form--col">
							<?php echo do_shortcode('[contact-form-7 id="1086" title="Contact form - Default" html_class="bx--form-item"]'); ?>
			      </div>

			    </div>
			  </div>

	<?php endwhile; ?>

<?php endif; ?>
