<?php if( have_rows('contact_us') ):

	while( have_rows('contact_us') ): the_row();

		// vars
		$heading = get_sub_field('heading');
    $paragraph = get_sub_field('paragraph');

		?>

		<div class="bx--grid about-us-form section-6rem">
		  <div class="bx--row">

		    	<div class="bx--col-lg-6 bx--col-xs-12 about-us-form--col">
		      	<h3 class="bx--type-beta"><?= $heading ?></h3>
		      	<p class="bx--type-delta_paragraph"><?= $paragraph ?></p>
		    	</div>

		    	<div class="bx--col-lg-6 bx--col-md-3 bx--col-xs-12 about-us-form--col">
						<?php echo do_shortcode('[contact-form-7 id="29" title="Contact form - About us" html_class="bx--form-item"]'); ?>
		      </div>

		    </div>
		  </div>

	<?php endwhile; ?>

<?php endif; ?>
