<div class="contact-form">

  <div class="contact-form--container">

    <div class="card form whitepaper no-link">

        	<h3 class="contact-form__heading heading-four"><?= $heading ?></h3>
        	<p class="contact-form__paragraph paragraph-sm"><?= $paragraph ?></p>

    			<?php echo do_shortcode('[contact-form-7 id="678" title="Contact form - Whitepaper" html_class="bx--form-item"]'); ?>

    </div>
  </div>
  <div class="bg-green">

  </div>
</div>
