<div class="ly--form-item">
  <strong class="ly--label">Account photo</strong>
  <p class="ly--label-description">only .jpg and .png files. 500kb max file size.</p>
  <div class="ly--file" data-file>
    <label
      for="your-file-importer-id-here"
      class="ly--file-btn ly--btn ly--btn--secondary"
      role="button"
      tabindex="0">Add files</label>
    <input
      type="file"
      class="ly--file-input"
      id="your-file-importer-id-here"
      data-file-uploader
      data-target="[data-file-container]"
      multiple
    />
    <div data-file-container class="ly--file-container"></div>
  </div>
</div>




<label class="ly--label"> <p class="ly--type-caption">Namn*</p>
    [text* your-name class:ly--text-input placeholder "ex. Namn Namnsson"]
</label>

<label class="ly--label"> <p class="ly--type-caption">E-mail*</p>
    [text* your-email class:ly--text-input placeholder "ex. namn@mail.se"]
</label>

<label class="ly--label"> <p class="ly--type-caption">E-mail</p>
    [textarea your-message class:ly--text-area placeholder "Skriv ditt meddelande här"]
</label>


<div class="ly--form-item">

  <strong class="ly--label">Account photo</strong>
  <p class="ly--label-description">only .jpg and .png files. 500kb max file size.</p>

    <div class="ly--file-split">
      <div class="ly--file" data-file>
        <label
          for="your-file-importer-id-here"
          class="ly--file-btn ly--btn ly--btn--secondary"
          id="btn-resume"
          role="button"
          tabindex="0">CV</label>

          [file your-resume class:ly--file-input id:your-resume filetypes:pdf|png|jpeg|jpg
          limit:2mb]

        <div data-file-container class="ly--file-container"></div>
      </div>

     <div class="ly--file" data-file>
        <label
          for="your-file-importer-id-here"
          class="ly--file-btn ly--btn ly--btn--secondary"
          id="btn-bio"
          role="button"
          tabindex="0">Personligt brev</label>

          [file your-bio class:ly--file-input id:your-bio filetypes:pdf|png|jpeg|jpg
          limit:2mb]

        <div data-file-container class="ly--file-container"></div>
      </div>

    </div>
</div>


<div class="ly--form-item">
  [submit class:ly--btn class:ly--btn__secondary type:button "Skicka meddelande"]
</div>
