<?php

    // check if the flexible content field has rows of data
    if( have_rows('service_flexible') ):

         // loop through the rows of data
        while ( have_rows('service_flexible') ) : the_row();

            if( get_row_layout() == 'intro_section' ):

              $intro = get_sub_field('intro_paragraph'); ?>

              <div class="bx--grid section-default">
                <div class="bx--row row--center">
                  <div class="bx--col-xs-12 bx--col-md-8 bx--col-lg-6 section-1col"><p><?= get_sub_field('intro_paragraph'); ?></p></div>
                </div>
              </div>

          <?php elseif ( get_row_layout() == 'delivery_time_section' ):?>


            <?php if( have_rows('delivery_time') ):?>
              <div class="bx--grid bg-03 section-2rem">
                <div class="bx--row">

                <?php while ( have_rows('delivery_time') ) : the_row();?>

                  <div class="bx--col-xs-12 bx--col-sm-4 section-3col">
                    <div class="col--flexcenter cities">
                      <h6 class="revealer-0"><?= get_sub_field('city');?></h6>
                      <h4 class="bx--type-gamma revealer-100"><span class="count"><?= get_sub_field('hours');?></span>h <span class="count"><?= get_sub_field('minutes');?></span>min</h4>
                    </div>
                  </div>

            <?php endwhile;?>
              </div>
            </div>
          <?php endif;?>


          <?php elseif ( get_row_layout() == 'split_section' ):

              $image = get_sub_field('image');
              $alttext = get_sub_field('image_alt_text');
              $heading = get_sub_field('heading');
              $paragraph = get_sub_field('paragraph'); ?>

              <!--SECOND PARAGRAF SECTION-->
              <div class="fw--grid bg-01">
                <div class="fw--row">

                  <div class="fw--col-md-6 fw--col-sm-12 section-fw bg-img" alt="<?=$alttext;?>" style="background-image: url(<?=$image;?>"></div>
                  <div class="fw--col-md-6 fw--col-sm-12 section-fw ">
                    <h3 class="bx--type-beta revealer-0"><?=$heading;?></h3>
                    <p class="revealer-100"><?=$paragraph;?></p>
                  </div>

                </div>
              </div>

            <?php elseif ( get_row_layout() == 'advantages' ):?>
              <div class="bx--grid section-default bg-02">
                <div class="bx--col-xs-12 bx--col-md-12 bx--col-lg-12 section-1col"><h3 class="bx--type-beta type-center"><?= get_sub_field('heading'); ?></h3></div>

                <div class="bx--row">

                  <?php if( have_rows('card') ):?>

                  <?php while ( have_rows('card') ) : the_row();?>

                  <div class="bx--col-xs-12 bx--col-md-6 bx--col-lg-4 section-3col--card">

                  <div class="card-sm revealer-0">
                        <div class="card-img image card-half">
                          <div class="img-container--icon bg-img--acf" style="background-image: url('<?= get_sub_field('bg_image');?>');">
                              <img class="icon revealer-100" style="height: <?= get_sub_field('icon_size');?>px" alt="<?= get_sub_field('alt_text'); ?>" src="<?= get_sub_field('icon'); ?>"/>
                              <div class="overlay" style="opacity:<?= get_sub_field('overlay_opacity');?>;"></div>
                          </div>
                        </div>

                        <div class="card-content card-half">
                          <div class="text-container">
                            <h3><?= get_sub_field('sub-heading');?></h3>
                            <p><?= get_sub_field('paragraph');?></p>
                          </div>
                        </div>
                    </div>
                  </div>


              <?php endwhile;?>

            <?php endif;?>
              </div>
            </div>

          <?php elseif ( get_row_layout() == 'products_large' ):?>
            <div class="bx--grid section-default bg-03">
              <div class="bx--col-xs-12 bx--col-md-12 bx--col-lg-12 section-1col"><h3 class="bx--type-beta type-center"><?= get_sub_field('heading'); ?></h3></div>

              <div class="bx--row">

                <?php if( have_rows('card_lg') ):?>

                <?php while ( have_rows('card_lg') ) : the_row();?>



                  <div class="bx--col-xs-12 revealer-100">
                        <div class="card-lg product">

                            <div class="card-img image card-half">
                              <div class="img-container--icon bg-img--acf" style="background-image: url('<?= get_sub_field('bg_image');?>');">
                                <img class="featured-image icon revealer-100" alt="<?= get_sub_field('alt_text'); ?>" src="<?= get_sub_field('icon'); ?>"/>
                                <div class="overlay" style="opacity:<?= get_sub_field('overlay_opacity');?>;"></div>
                                <button class="bx--btn bx--btn--secondary-white btn modal" type="button"><?= get_sub_field('btn_label');?></button>
                              </div>
                            </div>

                            <div class="card-content card-half">
                              <div class="text-container">
                                <h3 class="heading"><?= get_sub_field('heading');?></h3>
                                <p class="paragraph"><?= get_sub_field('paragraph');?></p>
                              </div>
                              <div class="info-container">
                                <div class="col-1">
                                  <h4 class="sub-heading"><?= get_sub_field('sub_heading_col1');?></h4>
                                  <p class="micro-heading bx--type-caption"><?= get_sub_field('micro_heading_col1');?></p>
                                  <p class="sub-paragraph"><?= get_sub_field('sub_paragraph_col1');?></p>
                                </div>
                                <div class="col-2">
                                  <h4 class="sub-heading"><?= get_sub_field('sub_heading_col2');?></h4>
                                  <p class="micro-heading bx--type-caption"><?= get_sub_field('micro_heading_col2');?></p>
                                  <p class="sub-paragraph"><?= get_sub_field('sub_paragraph_col2');?></p>
                                </div>
                              </div>

                            </div>
                        </div>
                  </div>

            <?php endwhile;?>

          <?php endif;?>
            </div>
          </div>

        <?php elseif ( get_row_layout() == 'products_small' ):?>

          <div class="bx--grid section-default bg-03">
            <div class="bx--col-xs-12 bx--col-md-12 bx--col-lg-12 section-1col"><h3 class="bx--type-beta type-center"><?= get_sub_field('heading'); ?></h3></div>

            <div class="bx--row">

                  <?php if( have_rows('card_sm') ):?>

                    <?php while ( have_rows('card_sm') ) : the_row();?>

                    <div class="bx--col-xs-12 bx--col-md-6 bx--col-lg-4 section-3col--card">

                    <div class="card-sm product revealer-0">
                          <div class="card-img image card-half">
                            <div class="img-container--icon bg-img--acf" style="background-image: url('<?= get_sub_field('bg_image');?>');">
                              <img class="featured-image icon revealer-100" style="height: <?= get_sub_field('icon_size');?>px;" alt="<?= get_sub_field('alt_text'); ?>" src="<?= get_sub_field('icon'); ?>"/>
                              <div class="overlay" style="opacity:<?= get_sub_field('overlay_opacity');?>;"></div>
                              <img class="flag" src="<?= get_sub_field('flag'); ?>"/>
                              <button class="bx--btn bx--btn--sm bx--btn--secondary-white btn modal" type="button"><?= get_sub_field('btn_label');?></button>
                            </div>
                          </div>

                          <div class="card-content card-half">
                            <div class="text-container">
                              <h3 class="heading"><?= get_sub_field('heading');?></h3>
                              <?php

                                  // check if the repeater field has rows of data
                                  if( have_rows('values') ):?>
                                    <div class="values-container">

                                   	<?php // loop through the rows of data
                                      while ( have_rows('values') ) : the_row();?>

                                        <p class="text-label"><?= get_sub_field('label');?>:</p><p class="text-value"><?= get_sub_field('value');?></p>

                                    <?php endwhile;?>

                                    </div>

                                <?php else :

                                      // no rows found

                                  endif;

                                  ?>

                            </div>
                            <div class="info-container">
                              <div class="col-1">
                                <h4 class="sub-heading"><?= get_sub_field('sub_heading_col1');?></h4>
                                <p class="micro-heading bx--type-caption"><?= get_sub_field('micro_heading_col1');?></p>
                              </div>

                            </div>

                          </div>
                      </div>
                    </div>


                <?php endwhile;?>

              <?php endif;?>
                </div>
              </div>

        <?php elseif ( get_row_layout() == 'cta_section' ):

                  // vars
                  $heading = get_sub_field('heading');
                  $paragraph = get_sub_field('paragraph');
                  $btnlabel = get_sub_field('btn_label');
                  $bgimg = get_sub_field('bg_img');
                  $overlay = get_sub_field('overlay');?>

                  <div class="ctasection bg-img--acf" <?php if (get_sub_field('bg_img')):?>style="background-size: cover; background-repeat: no-repeat; background-image: url('<?= $bgimg; ?>');"<?php endif;?>>

                    <div class="ctasection-container">
                      <div class="ctasection-text revealer-0">
                        <h4 class="bx--type-gamma"><?= $heading; ?></h4>
                        <p><?= $paragraph; ?></p>
                      </div>

                      <?php if (get_sub_field('link')) :?><a href="<?= get_sub_field('link');?>"><button class="bx--btn bx--btn--secondary-white revealer-0" type="button"><?= $btnlabel; ?></button></a>
                      <?php else :?> <button class="bx--btn bx--btn--secondary-white modal revealer-0" type="button"><?= $btnlabel; ?></button>
                      <?php endif;?>

                    </div>
                    <div class="overlay" style="opacity:<?= $overlay; ?>;"></div>
                  </div>


          <?php elseif ( get_row_layout() == 'faq_section' ):?>

            <div class="bx--grid section-default bg-01 faq air">
              <div class="bx--col-xs-12 bx--col-md-12 bx--col-lg-12 section-1col"><h3 class="bx--type-beta"><?= get_sub_field('faq_heading');?></h3></div>
                <div class="bx--row">


                <?php if( have_rows('faq_col1') ):
                  $i = 0;
                  $number = ++$i;
                  ?>
                  <div class="bx--col-xs-12 bx--col-md-6 section-2col accordion-1">

                        <ul data-accordion class="bx--accordion revealer-0">

                <?php while ( have_rows('faq_col1') ) : the_row();?>

                  <li data-accordion-item class="bx--accordion__item">
                    <button class="bx--accordion__heading" aria-expanded="false" aria-controls="pane<?= $number;?>">
                      <svg class="bx--accordion__arrow" width="5" height="10" viewBox="0 0 5 10" fill-rule="evenodd">
                        <path d="M0 0L5  5 0 10z"></path>
                      </svg>
                      <p class="bx--accordion__title"><?= get_sub_field('question'); ?></p>
                    </button>
                    <div id="pane<?= $number;?>" class="bx--accordion__content">
                      <p><?= get_sub_field('answer'); ?></p>
                    </div>
                  </li>


            <?php endwhile;?>
                  </ul>
                </div>
          <?php endif;?>
          <?php if( have_rows('faq_col2') ):
            $i = 0;
            $number = ++$i;
            ?>
            <div class="bx--col-xs-12 bx--col-md-6 section-2col accordion-2">

                  <ul data-accordion class="bx--accordion revealer-100">

          <?php while ( have_rows('faq_col2') ) : the_row();?>

            <li data-accordion-item class="bx--accordion__item">
              <button class="bx--accordion__heading" aria-expanded="false" aria-controls="pane<?= $number;?>">
                <svg class="bx--accordion__arrow" width="5" height="10" viewBox="0 0 5 10" fill-rule="evenodd">
                  <path d="M0 0L5  5 0 10z"></path>
                </svg>
                <p class="bx--accordion__title"><?= get_sub_field('question'); ?></p>
              </button>
              <div id="pane<?= $number;?>" class="bx--accordion__content">
                <p><?= get_sub_field('answer'); ?></p>
              </div>
            </li>


      <?php endwhile;?>
            </ul>
          </div>
    <?php endif;?>
            </div>
          </div>

    <?php endif;
          endwhile;
          else :

              alert('no flexible found');

          endif;?>
