<?php if( have_rows('section-services') ):

	while( have_rows('section-services') ): the_row();

		// vars
    $subheading = get_sub_field('subheading');
    $heading = get_sub_field('heading');
		$btnlink = get_sub_field('btn_link');
		$url = $btnlink["url"];
		$label = $btnlink["title"];

		?>
    <div class="bx--grid services-sm section-4rem">
      <div class="bx--row">

	        <div class="bx--col-lg-12 section-heading">
	          <h5 class="bx--type-delta__subheading"><?= $subheading ?></h5>
	          <h2 class="bx--type-alpha"><?= $heading ?></h2>
	        </div>

        <div class="bx--col-lg-12 section-wrap">

          <?php

                $front = array(
                    'post_type' => 'services',
                    'orderby' => 'date',
                    'order'   => 'DESC',
                    'posts_per_page' => 6,
                );

								$services = array(
										'post_type' => 'services',
										'orderby' => 'title',
										'order'   => 'ASC',
										'posts_per_page' => -1,
								);

								if ( is_front_page() ) {
									$query = new WP_Query( $front );
								} else {
									$query = new WP_Query( $services );
								}

                ?>

                <?php while ( $query->have_posts() ) : $query->the_post();?>

									<div class="bx--card revealer-<?= $i++ * 100 ?> section-2col">

                  	<?php include( get_template_directory() . '/phtml/sections/cards/card-service.phtml');?>

									</div>
              <?php  endwhile; ?>

                <?php
                wp_reset_postdata();?>

        </div>

				<?php if ( is_front_page() ): ?>

	        <div class="bx--col-lg-12 section-button_center">
	          <a href="<?= $url ?>"><button class="bx--btn bx--btn__secondary" type="button"><?= $label ?></button></a>
	        </div>

				<?php else: ?>

				<?php endif;?>


      </div>
    </div>
	<?php endwhile; ?>

<?php endif; ?>
