
<?php if( have_rows('content_switcher_repeater') ): ?>

	<div class="grid section-2rem">
		<div class="row">
			<div data-content-switcher class="ly--content-switcher">

	<?php while( have_rows('content_switcher_repeater') ): the_row();

		// vars
		$image = get_sub_field('image');
		$content = get_sub_field('content');
		$link = get_sub_field('link');

		?>

		<button class="ly--content-switcher-btn ly--content-switcher--selected" data-target=".demo--panel2--opt-1">
			<svg class="ly--content-switcher__icon" width="16" height="16" viewBox="0 0 16 16">
				<path d="M8 0C3.6 0 0 3.6 0 8s3.6 8 8 8 8-3.6 8-8-3.6-8-8-8zm4 9H9v3H7V9H4V7h3V4h2v3h3v2z"></path>
			</svg>
			First section
		</button>

	<?php endwhile; ?>

			</div>
		</div>
	</div>

<?php endif; ?>
