<ul data-dropdown data-value class="ly--dropdown ly--dropdown--up" tabindex="0">
  <li class="ly--dropdown-text">Dropdown label</li>
  <svg class="ly--dropdown__arrow" width="10" height="5" viewBox="0 0 10 5" fill-rule="evenodd">
    <path d="M10 0L5 5 0 0z"></path>
  </svg>
  <li>
    <ul class="ly--dropdown-list">
      <li data-option data-value="all" class="ly--dropdown-item">
        <a class="ly--dropdown-link" href="javascript:void(0)">Option 1</a>
      </li>
      <li data-option data-value="cloudFoundry" class="ly--dropdown-item">
        <a class="ly--dropdown-link" href="javascript:void(0)">Option 2</a>
      </li>
      <li data-option data-value="staging" class="ly--dropdown-item">
        <a class="ly--dropdown-link" href="javascript:void(0)">Option 3</a>
      </li>
      <li data-option data-value="dea" class="ly--dropdown-item">
        <a class="ly--dropdown-link" href="javascript:void(0)">Option 4</a>
      </li>
      <li data-option data-value="router" class="ly--dropdown-item">
        <a class="ly--dropdown-link" href="javascript:void(0)">Option 5</a>
      </li>
    </ul>
  </li>
</ul>
