<?php if ( have_rows('section_cta') ):

        while( have_rows('section_cta') ): the_row();
        // vars
        $heading = get_sub_field('heading');
        $paragraph = get_sub_field('paragraph');
        $btnlink = get_sub_field('btn_link');
        $theme = get_sub_field('theme');
        $url = $btnlink["url"];
        $label = $btnlink["title"];

?>

    <div class="bx--grid cta-section <?php if ( $theme == 1 ) { echo 'primary'; } elseif ( $theme == 2 ) { echo 'secondary'; } else { echo 'dark'; } ?>">
      <div class="bx--row">
        <div class="bx--col cta-section-container">

          <div class="text-container">

            <h3 class="text-container_heading"><?= @$heading ?></h3>

            <?php if ($paragraph):?>
              <p class="text-container_paragraph bx--type-epsilon__paragraph"><?= @$paragraph ?></p>
            <?php endif;?>

          </div>

          <a href="<?= $url ?>">
            <button class="bx--btn <?php if ( $theme == 1 ) { echo 'bx--btn--outline__white'; } elseif ( $theme == 2 ) { echo 'bx--btn--outline__white'; } else { echo 'bx--btn--outline__white'; } ?>" type="button">
              <?= $label ?>
            </button>
          </a>

        </div>

      </div>
    </div>

<?php endwhile;?>
<?php endif; ?>
