<div class="ly--form-item">
  <label for="slider" class="ly--label">Slider label</label>
  <div class="ly--slider-test">
  <div class="ly--slider-container">
    <span class="ly--slider__range-label">0</span>
    <div class="ly--slider" data-slider data-slider-input-box="#slider-input-box">
      <div class="ly--slider__track"></div>
      <div class="ly--slider__filled-track"></div>
      <div class="ly--slider__thumb" tabindex="0"></div>
      <input id="slider" class="ly--slider__input" type="range" step="1" min="0" max="100" value="50">
    </div>
    <span class="ly--slider__range-label">100</span>
    <input id="slider-input-box" type="number" class="ly--text-input ly--slider-text-input" placeholder="0">
  </div>
</div>
</div>
