<?php if( have_rows('our_offer') ):

	while( have_rows('our_offer') ): the_row();

		// vars
		$subheading = get_sub_field('subheading');
		$heading = get_sub_field('heading');

    $icon1 = get_sub_field('icon_one');
    $heading1 = get_sub_field('heading_one');
    $paragraph1 = get_sub_field('paragraph_one');

		?>

    <div class="bx--grid our-offer section-6rem">
      <div class="bx--row">

        <div class="bx--col-lg-12 section-heading">
          <h5 class="sub-heading-two"><?= $subheading ?></h5>
          <h2 class="heading-three"><?= $heading ?></h2>
        </div>

        <?php if( have_rows('our_offer_icons') ):

							$n = 0;

					?>

      	<?php while( have_rows('our_offer_icons') ): the_row();

      		// vars
      		$icon = get_sub_field('icon');
      		$heading = get_sub_field('heading');
      		$paragraph = get_sub_field('paragraph');
					$i = $n++ * 100;
      		?>

					<div class="interactive-icon">
						<div class="interactive-icon__icon">
							<img src="<?= $icon ?>" />
						</div>
						<h5 class="interactive-icon__heading bx--type-delta__subheading"><?= $heading ?></h5>
						<div class="interactive-icon--text-container">
							<p class="interactive-icon__paragraph bx--type-epsilon"><?= $paragraph ?></p>
						</div>
					</div>

      	<?php endwhile; ?>

      <?php endif; ?>


      </div>

    </div>


	<?php endwhile; ?>

<?php endif; ?>
