<section class="ly--structured-list">
  <div class="ly--structured-list-thead">
    <div class="ly--structured-list-row ly--structured-list-row--header-row">
      <div class="ly--structured-list-th">ColumnA</div>
      <div class="ly--structured-list-th">ColumnB</div>
      <div class="ly--structured-list-th">ColumnC</div>
    </div>
  </div>
  <div class="ly--structured-list-tbody">
    <div class="ly--structured-list-row">
      <div class="ly--structured-list-td ly--structured-list-content--nowrap">Row 1</div>
      <div class="ly--structured-list-td">Row 1</div>
      <div class="ly--structured-list-td">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc dui magna, finibus id tortor sed, aliquet bibendum augue. Aenean posuere sem vel euismod dignissim. Nulla ut cursus dolor. Pellentesque vulputate nisl a porttitor interdum.
      </div>
    </div>
    <div class="ly--structured-list-row">
      <div class="ly--structured-list-td ly--structured-list-content--nowrap">Row 2</div>
      <div class="ly--structured-list-td">
        Row 2
      </div>
      <div class="ly--structured-list-td">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc dui magna, finibus id tortor sed, aliquet bibendum augue. Aenean posuere sem vel euismod dignissim. Nulla ut cursus dolor. Pellentesque vulputate nisl a porttitor interdum.
      </div>
    </div>
  </div>
</section>
