<div class="ly--data-table-v2-container" data-table-v2>
  <h4 class="ly--data-table-v2-header">Table title</h4>
  <section class="ly--table-toolbar">
    <div class="ly--batch-actions" aria-label="Table Action Bar">
      <div class="ly--action-list">
        <button class="ly--btn ly--btn--sm ly--btn--ghost" type="button">
          Ghost
          <svg class="ly--btn__icon" width="16" height="16" viewBox="0 0 16 16" fill-rule="evenodd">
            <path d="M8 0C3.6 0 0 3.6 0 8s3.6 8 8 8 8-3.6 8-8-3.6-8-8-8zm4 9H9v3H7V9H4V7h3V4h2v3h3v2z"></path>
          </svg>
        </button>

        <button class="ly--btn ly--btn--sm ly--btn--ghost" type="button">
          Ghost
          <svg class="ly--btn__icon" width="16" height="16" viewBox="0 0 16 16" fill-rule="evenodd">
            <path d="M8 0C3.6 0 0 3.6 0 8s3.6 8 8 8 8-3.6 8-8-3.6-8-8-8zm4 9H9v3H7V9H4V7h3V4h2v3h3v2z"></path>
          </svg>
        </button>

        <button class="ly--btn ly--btn--sm ly--btn--ghost" type="button">
          Ghost
          <svg class="ly--btn__icon" width="16" height="16" viewBox="0 0 16 16" fill-rule="evenodd">
            <path d="M8 0C3.6 0 0 3.6 0 8s3.6 8 8 8 8-3.6 8-8-3.6-8-8-8zm4 9H9v3H7V9H4V7h3V4h2v3h3v2z"></path>
          </svg>
        </button>
      </div>
      <div class="ly--batch-summary">
        <p class="ly--batch-summary__para">
          <span data-items-selected>3</span> items selected</p>
        <button data-event="action-bar-cancel" class="ly--batch-summary__cancel">Cancel</button>
      </div>
    </div>
    <div class="ly--toolbar-search-container">
      <div data-search class="ly--search ly--search--sm" role="search">
        <svg class="ly--search-magnifier" width="16" height="16" viewBox="0 0 16 16" fill-rule="evenodd">
          <path d="M6 2c2.2 0 4 1.8 4 4s-1.8 4-4 4-4-1.8-4-4 1.8-4 4-4zm0-2C2.7 0 0 2.7 0 6s2.7 6 6 6 6-2.7 6-6-2.7-6-6-6zM16 13.8L13.8 16l-3.6-3.6 2.2-2.2z"></path>
          <path d="M16 13.8L13.8 16l-3.6-3.6 2.2-2.2z"></path>
        </svg>
        <label id="search-input-label-10" class="ly--label" for="search__input-10">Filter table</label>
        <input class="ly--search-input" type="text" id="search__input-10" role="search" placeholder="Filter table" aria-labelledby="search-input-label-10">
        <svg class="ly--search-close ly--search-close--hidden" width="10" height="10" viewBox="0 0 10 10" fill-rule="evenodd">
          <path d="M9.8 8.6L8.4 10 5 6.4 1.4 10 0 8.6 3.6 5 .1 1.4 1.5 0 5 3.6 8.6 0 10 1.4 6.4 5z"></path>
        </svg>
      </div>
    </div>

    <div class="ly--toolbar-content">
      <button class="ly--toolbar-action">
        <svg class="ly--toolbar-action__icon" width="16" height="16" viewBox="-1 2 16 16">
          <path d="M8 9V2H6.1v7L3.5 6.5 2 8l5 5 5-5-1.5-1.5L8 9z" />
          <path d="M13 12v3H1v-3h-2v6h16v-6h-2z" />
        </svg>
      </button>

      <button class="ly--toolbar-action">
        <svg class="ly--toolbar-action__icon" width="16" height="16" viewBox="0 0 16 16" fill-rule="evenodd">
          <path d="M2.032 10.924l7.99-7.99 2.97 2.97-7.99 7.99zM11.046 2.014l1.98-1.98 2.97 2.97-1.98 1.98zM0 16l3-1-2-2z"></path>
        </svg>
      </button>

      <button class="ly--toolbar-action">
        <svg class="ly--toolbar-action__icon" width="16" height="16" viewBox="-1 2 16 16">
          <path d="M13.1 10c0-.3 0-.6-.1-1l2-1.7-1.7-2.7-2.3.8c-.6-.5-1.2-.9-1.9-1.1L8.6 2H5.4l-.5 2.2c-.7.3-1.4.7-1.9 1.2L.7 4.6-1 7.3.9 9c0 .3-.1.6-.1 1s0 .6.1 1L-1 12.7l1.7 2.7 2.3-.8c.6.5 1.2.9 1.9 1.1l.5 2.3h3.2l.5-2.2c.7-.3 1.3-.6 1.9-1.1l2.3.8 1.7-2.7-1.9-1.8v-1zM7 12c-1.1 0-2-.9-2-2s.9-2 2-2 2 .9 2 2-.9 2-2 2z"
          />
        </svg>
      </button>

      <button class="ly--btn ly--btn--sm ly--btn__primary">Add new</button>
    </div>


  </section>
  <table class="ly--data-table-v2">
    <thead>
      <tr>
        <th>
          <input data-event="select-all" id="ly--checkbox-90" class="ly--checkbox" type="checkbox" value="green" name="checkbox-20">
          <label for="ly--checkbox-90" class="ly--checkbox-label" aria-label="Label name">
            <span class="ly--checkbox-appearance">
              <svg class="ly--checkbox-checkmark" width="12" height="9" viewBox="0 0 12 9" fill-rule="evenodd">
                <path d="M4.1 6.1L1.4 3.4 0 4.9 4.1 9l7.6-7.6L10.3 0z"></path>
              </svg>
            </span>
          </label>
        </th>
        <th>
          <button class="ly--table-sort-v2" data-event="sort">
            <span class="ly--table-header-label">Name</span>
            <svg class="ly--table-sort-v2__icon" width='10' height='5' viewBox='0 0 10 5' fill-rule='evenodd'>
              <path d='M10 0L5 5 0 0z'></path>
            </svg>
          </button>
        </th>
        <th>
          <button class="ly--table-sort-v2" data-event="sort">
            <span>Protocol</span>
            <svg class="ly--table-sort-v2__icon" width='10' height='5' viewBox='0 0 10 5' fill-rule='evenodd'>
              <path d='M10 0L5 5 0 0z'></path>
            </svg>
          </button>
        </th>
        <th>
          <button class="ly--table-sort-v2" data-event="sort">
            <span>Something</span>
            <svg class="ly--table-sort-v2__icon" width='10' height='5' viewBox='0 0 10 5' fill-rule='evenodd'>
              <path d='M10 0L5 5 0 0z'></path>
            </svg>
          </button>
        </th>
        <th>
          <button class="ly--table-sort-v2" data-event="sort">
            <span>Rule</span>
            <svg class="ly--table-sort-v2__icon" width='10' height='5' viewBox='0 0 10 5' fill-rule='evenodd'>
              <path d='M10 0L5 5 0 0z'></path>
            </svg>
          </button>
        </th>
        <th>
          <button class="ly--table-sort-v2" data-event="sort">
            <span>Attached Groups</span>
            <svg class="ly--table-sort-v2__icon" width='10' height='5' viewBox='0 0 10 5' fill-rule='evenodd'>
              <path d='M10 0L5 5 0 0z'></path>
            </svg>
          </button>
        </th>
        <th>
          <button class="ly--table-sort-v2" data-event="sort">
            <span>Status</span>
            <svg class="ly--table-sort-v2__icon" width='10' height='5' viewBox='0 0 10 5' fill-rule='evenodd'>
              <path d='M10 0L5 5 0 0z'></path>
            </svg>
          </button>
        </th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
          <input data-event="select" id="ly--checkbox-91" class="ly--checkbox" type="checkbox" value="green" name="checkbox-13">
          <label for="ly--checkbox-91" class="ly--checkbox-label" aria-label="Label name">
            <span class="ly--checkbox-appearance">
              <svg class="ly--checkbox-checkmark" width="12" height="9" viewBox="0 0 12 9" fill-rule="evenodd">
                <path d="M4.1 6.1L1.4 3.4 0 4.9 4.1 9l7.6-7.6L10.3 0z"></path>
              </svg>
            </span>
          </label>
        </td>
        <td>Load Balancer 1</td>
        <td>HTTP</td>
        <td>80</td>
        <td>Round Robin</td>
        <td>Maureen's VM Groups</td>
        <td>Active</td>
        <td class="ly--table-overflow">
          <div data-overflow-menu tabindex="0" aria-label="Overflow menu description" class="ly--overflow-menu">
            <svg class="ly--overflow-menu__icon" width="4" height="20" viewBox="0 0 4 20" fill-rule="evenodd">
              <circle cx="2" cy="2" r="2"></circle>
              <circle cx="2" cy="10" r="2"></circle>
              <circle cx="2" cy="18" r="2"></circle>
            </svg>
            <ul class="ly--overflow-menu-options ly--overflow-menu--flip">
              <li class="ly--overflow-menu-options__option">
                <button class="ly--overflow-menu-options__btn">Stop app</button>
              </li>
              <li class="ly--overflow-menu-options__option">
                <button class="ly--overflow-menu-options__btn">Restart app</button>
              </li>
              <li class="ly--overflow-menu-options__option">
                <button class="ly--overflow-menu-options__btn">Rename app</button>
              </li>
              <li class="ly--overflow-menu-options__option">
                <button class="ly--overflow-menu-options__btn">Edit routes and access, use title when</button>
              </li>
              <li class="ly--overflow-menu-options__option ly--overflow-menu-options__option--danger">
                <button class="ly--overflow-menu-options__btn">Delete app</button>
              </li>
            </ul>
          </div>
        </td>
      </tr>
      <tr class="expandable-row">
        <td>
          <input data-event="select" id="ly--checkbox-92" class="ly--checkbox" type="checkbox" value="green" name="checkbox-14">
          <label for="ly--checkbox-92" class="ly--checkbox-label" aria-label="Label name">
            <span class="ly--checkbox-appearance">
              <svg class="ly--checkbox-checkmark" width="12" height="9" viewBox="0 0 12 9" fill-rule="evenodd">
                <path d="M4.1 6.1L1.4 3.4 0 4.9 4.1 9l7.6-7.6L10.3 0z"></path>
              </svg>
            </span>
          </label>
        </td>
        <td>Load Balancer 5</td>
        <td>HTTP</td>
        <td>80</td>
        <td>Round Robin</td>
        <td>Maureen's VM Groups</td>
        <td>Active</td>
        <td class="ly--table-overflow">
          <div data-overflow-menu tabindex="0" aria-label="Overflow menu description" class="ly--overflow-menu">
            <svg class="ly--overflow-menu__icon" width="4" height="20" viewBox="0 0 4 20" fill-rule="evenodd">
              <circle cx="2" cy="2" r="2"></circle>
              <circle cx="2" cy="10" r="2"></circle>
              <circle cx="2" cy="18" r="2"></circle>
            </svg>
            <ul class="ly--overflow-menu-options ly--overflow-menu--flip">
              <li class="ly--overflow-menu-options__option">
                <button class="ly--overflow-menu-options__btn">Stop app</button>
              </li>
              <li class="ly--overflow-menu-options__option">
                <button class="ly--overflow-menu-options__btn">Restart app</button>
              </li>
              <li class="ly--overflow-menu-options__option">
                <button class="ly--overflow-menu-options__btn">Rename app</button>
              </li>
              <li class="ly--overflow-menu-options__option">
                <button class="ly--overflow-menu-options__btn">Edit routes and access, use title when</button>
              </li>
              <li class="ly--overflow-menu-options__option ly--overflow-menu-options__option--danger">
                <button class="ly--overflow-menu-options__btn">Delete app</button>
              </li>
            </ul>
          </div>
        </td>
      </tr>
      <tr>
        <td>
          <input data-event="select" id="ly--checkbox-93" class="ly--checkbox" type="checkbox" value="green" name="checkbox-15">
          <label for="ly--checkbox-93" class="ly--checkbox-label" aria-label="Label name">
            <span class="ly--checkbox-appearance">
              <svg class="ly--checkbox-checkmark" width="12" height="9" viewBox="0 0 12 9" fill-rule="evenodd">
                <path d="M4.1 6.1L1.4 3.4 0 4.9 4.1 9l7.6-7.6L10.3 0z"></path>
              </svg>
            </span>
          </label>
        </td>
        <td>Load Balancer 5</td>
        <td>HTTP</td>
        <td>80</td>
        <td>Round Robin</td>
        <td>Maureen's VM Groups</td>
        <td>Active</td>
        <td class="ly--table-overflow">
          <div data-overflow-menu tabindex="0" aria-label="Overflow menu description" class="ly--overflow-menu">
            <svg class="ly--overflow-menu__icon" width="4" height="20" viewBox="0 0 4 20" fill-rule="evenodd">
              <circle cx="2" cy="2" r="2"></circle>
              <circle cx="2" cy="10" r="2"></circle>
              <circle cx="2" cy="18" r="2"></circle>
            </svg>
            <ul class="ly--overflow-menu-options ly--overflow-menu--flip">
              <li class="ly--overflow-menu-options__option">
                <button class="ly--overflow-menu-options__btn">Stop app</button>
              </li>
              <li class="ly--overflow-menu-options__option">
                <button class="ly--overflow-menu-options__btn">Restart app</button>
              </li>
              <li class="ly--overflow-menu-options__option">
                <button class="ly--overflow-menu-options__btn">Rename app</button>
              </li>
              <li class="ly--overflow-menu-options__option">
                <button class="ly--overflow-menu-options__btn">Edit routes and access, use title when</button>
              </li>
              <li class="ly--overflow-menu-options__option ly--overflow-menu-options__option--danger">
                <button class="ly--overflow-menu-options__btn">Delete app</button>
              </li>
            </ul>
          </div>
        </td>
      </tr>
      <tr>
        <td>
          <input data-event="select" id="ly--checkbox-94" class="ly--checkbox" type="checkbox" value="green" name="checkbox-11">
          <label for="ly--checkbox-94" class="ly--checkbox-label" aria-label="Label name">
            <span class="ly--checkbox-appearance">
              <svg class="ly--checkbox-checkmark" width="12" height="9" viewBox="0 0 12 9" fill-rule="evenodd">
                <path d="M4.1 6.1L1.4 3.4 0 4.9 4.1 9l7.6-7.6L10.3 0z"></path>
              </svg>
            </span>
          </label>
        </td>
        <td>Load Balancer 5</td>
        <td>HTTP</td>
        <td>80</td>
        <td>Round Robin</td>
        <td>Maureen's VM Groups</td>
        <td>Active</td>
        <td class="ly--table-overflow">
          <div data-overflow-menu tabindex="0" aria-label="Overflow menu description" class="ly--overflow-menu">
            <svg class="ly--overflow-menu__icon" width="4" height="20" viewBox="0 0 4 20" fill-rule="evenodd">
              <circle cx="2" cy="2" r="2"></circle>
              <circle cx="2" cy="10" r="2"></circle>
              <circle cx="2" cy="18" r="2"></circle>
            </svg>
            <ul class="ly--overflow-menu-options ly--overflow-menu--flip">
              <li class="ly--overflow-menu-options__option">
                <button class="ly--overflow-menu-options__btn">Stop app</button>
              </li>
              <li class="ly--overflow-menu-options__option">
                <button class="ly--overflow-menu-options__btn">Restart app</button>
              </li>
              <li class="ly--overflow-menu-options__option">
                <button class="ly--overflow-menu-options__btn">Rename app</button>
              </li>
              <li class="ly--overflow-menu-options__option">
                <button class="ly--overflow-menu-options__btn">Edit routes and access, use title when</button>
              </li>
              <li class="ly--overflow-menu-options__option ly--overflow-menu-options__option--danger">
                <button class="ly--overflow-menu-options__btn">Delete app</button>
              </li>
            </ul>
          </div>
        </td>
      </tr>
      <tr>
        <td>
          <input data-event="select" id="ly--checkbox-95" class="ly--checkbox" type="checkbox" value="green" name="checkbox-12">
          <label for="ly--checkbox-95" class="ly--checkbox-label" aria-label="Label name">
            <span class="ly--checkbox-appearance">
              <svg class="ly--checkbox-checkmark" width="12" height="9" viewBox="0 0 12 9" fill-rule="evenodd">
                <path d="M4.1 6.1L1.4 3.4 0 4.9 4.1 9l7.6-7.6L10.3 0z"></path>
              </svg>
            </span>
          </label>
        </td>
        <td>Load Balancer 5</td>
        <td>HTTP</td>
        <td>80</td>
        <td>Round Robin</td>
        <td>Maureen's VM Groups</td>
        <td>Active</td>
        <td class="ly--table-overflow">
          <div data-overflow-menu tabindex="0" aria-label="Overflow menu description" class="ly--overflow-menu">
            <svg class="ly--overflow-menu__icon" width="4" height="20" viewBox="0 0 4 20" fill-rule="evenodd">
              <circle cx="2" cy="2" r="2"></circle>
              <circle cx="2" cy="10" r="2"></circle>
              <circle cx="2" cy="18" r="2"></circle>
            </svg>
            <ul class="ly--overflow-menu-options ly--overflow-menu--flip">
              <li class="ly--overflow-menu-options__option">
                <button class="ly--overflow-menu-options__btn">Stop app</button>
              </li>
              <li class="ly--overflow-menu-options__option">
                <button class="ly--overflow-menu-options__btn">Restart app</button>
              </li>
              <li class="ly--overflow-menu-options__option">
                <button class="ly--overflow-menu-options__btn">Rename app</button>
              </li>
              <li class="ly--overflow-menu-options__option">
                <button class="ly--overflow-menu-options__btn">Edit routes and access, use title when</button>
              </li>
              <li class="ly--overflow-menu-options__option ly--overflow-menu-options__option--danger">
                <button class="ly--overflow-menu-options__btn">Delete app</button>
              </li>
            </ul>
          </div>
        </td>
      </tr>
    </tbody>
  </table>
</div>
<div class="ly--pagination" data-pagination>
  <div class="ly--pagination__left">
    <span class="ly--pagination__text">Items per page:</span>
    <div class="ly--select ly--select--inline">
      <label for="select-id-pagination" class="ly--visually-hidden">Number of items per page</label>
      <select id="select-id-pagination" class="ly--select-input" data-items-per-page>
        <option class="ly--select-option" value="10" selected>10</option>
        <option class="ly--select-option" value="20">20</option>
        <option class="ly--select-option" value="30">30</option>
        <option class="ly--select-option" value="40">40</option>
        <option class="ly--select-option" value="50">50</option>
      </select>
      <svg class="ly--select__arrow" width="10" height="5" viewBox="0 0 10 5" fill-rule="evenodd">
        <path d="M10 0L5 5 0 0z"></path>
      </svg>
    </div>
    <span class="ly--pagination__text">
      <span>|&nbsp;</span>
      <span data-displayed-item-range>1-10</span> of
      <span data-total-items>40</span> items</span>
  </div>
  <div class="ly--pagination__right ly--pagination--inline">
    <span class="ly--pagination__text">
      <span data-displayed-page-number>1</span> of
      <span data-total-pages>4</span> pages</span>
    <button class="ly--pagination__button ly--pagination__button--backward" data-page-backward aria-label="Backward button">
      <svg class="ly--pagination__button-icon" width="8" height="12" viewBox="0 0 8 12" fill-rule="evenodd">
        <path d="M7.5 10.6L2.8 6l4.7-4.6L6.1 0 0 6l6.1 6z"></path>
      </svg>
    </button>
    <label for="page-number-input" class="ly--visually-hidden">Page number input</label>
    <div class="ly--select ly--select--inline">
      <label for="select-id-pagination" class="ly--visually-hidden">Number of items per page</label>
      <select id="select-id-pagination" class="ly--select-input" data-page-number-input>
        <option class="ly--select-option" value="1" selected>1</option>
        <option class="ly--select-option" value="2">2</option>
        <option class="ly--select-option" value="3">3</option>
        <option class="ly--select-option" value="4">4</option>
        <option class="ly--select-option" value="5">5</option>
      </select>
      <svg class="ly--select__arrow" width="10" height="5" viewBox="0 0 10 5" fill-rule="evenodd">
        <path d="M10 0L5 5 0 0z"></path>
      </svg>
    </div>
    <button class="ly--pagination__button ly--pagination__button--forward" data-page-forward aria-label="Forward button">
      <svg class="ly--pagination__button-icon" width="8" height="12" viewBox="0 0 8 12" fill-rule="evenodd">
        <path d="M0 10.6L4.7 6 0 1.4 1.4 0l6.1 6-6.1 6z"></path>
      </svg>
    </button>
  </div>
</div>
