<?php if( have_rows('section_client_logos') ):

	while( have_rows('section_client_logos') ): the_row();

		// vars
    $subheading = get_sub_field('subheading');
    $heading = get_sub_field('heading');

		?>

    <div class="bx--grid section-clients section-6rem">
      <div class="bx--row">

        <div class="bx--col-lg-12 bx--col-sm-6 section-heading">
          <h2 class="bx--type-beta"><?= $heading ?></h2>
        </div>


          <?php
          if( have_rows('client_logos') ): ?>

          <div class="bx--col-lg-12 bx--col-sm-12 clients">

          	<?php while( have_rows('client_logos') ): the_row();

          		// vars
          		$logo = get_sub_field('logo');
							$btnlink = get_sub_field('link');
							$url = $btnlink["url"];
							$label = $btnlink["title"];

          		?>
              <a class="client__link" href="<?= $url ?>" target="_blank">
          		    <div class="client__img-container">
                    <img class="client__logo" src="<?= $logo ?>" />
                </div>
              </a>
          	<?php endwhile; ?>

          </div>

          <?php endif; ?>


      </div>
    </div>

  <?php endwhile; ?>

<?php endif; ?>
