<?php

global $post;
?>

<?php if ( is_single() && $post->post_type == 'post' ):?>
<nav class="grid ly--breadcrumb ly--breadcrumb--no-trailing-slash post" aria-label="breadcrumb">
<?php elseif ( is_page_template('page-templates/about-us.php') ):?>
<nav class="grid ly--breadcrumb ly--breadcrumb--no-trailing-slash page--about-us" aria-label="breadcrumb">
<?php else: ?>
<nav class="grid ly--breadcrumb ly--breadcrumb--no-trailing-slash" aria-label="breadcrumb">
<?php endif; ?>

    <div class="row flex-start">

<?php if (!is_home()) :?>


    <div class="ly--breadcrumb-item">
      <a href="<?php echo get_home_url(); ?>" class="ly--link">
        <?php
          $frontpage_id = get_option( 'page_on_front' );
          echo get_the_title($frontpage_id);
        ?>
      </a>
    </div>

          <?php if ( is_single() ):

                  $title = get_the_title();

                      if ( $post->post_type == 'consultants' ): ?>

                          <div class="ly--breadcrumb-item">
                            <a href="<?php echo get_home_url() . '/konsulter' ?>" class="ly--link">
                              Konsulter
                            </a>
                          </div>

                          <div class="ly--breadcrumb-item">
                            <a class="ly--link_current">
                              <?php if ( strlen($title) > 40 ):

                                      echo substr($title, 0, 40).'...';

                                    else:

                                      echo $title;

                                    endif;
                              ?>
                            </a>
                          </div>
                          <?php
                      elseif ( $post->post_type == 'services' ): ?>

                          <div class="ly--breadcrumb-item">
                            <a href="<?php echo get_home_url() . '/tjanster' ?>" class="ly--link">
                              Tjänster
                            </a>
                          </div>

                          <div class="ly--breadcrumb-item">
                            <a class="ly--link_current">
                              <?php if ( strlen($title) > 40 ):

                                      echo substr($title, 0, 40).'...';

                                    else:

                                      echo $title;

                                    endif;
                              ?>
                            </a>
                          </div>

                          <?php
                      elseif ( $post->post_type == 'post' ): ?>

                              <div class="ly--breadcrumb-item">
                                <a href="<?php echo get_home_url() . '/resurser' ?>" class="ly--link">
                                  Resurser
                                </a>
                              </div>

                              <div class="ly--breadcrumb-item">
                                <a class="ly--link_current">
                                  <?php if ( strlen($title) > 40 ):

                                          echo substr($title, 0, 40).'...';

                                        else:

                                          echo $title;

                                        endif;
                                  ?>
                                </a>
                              </div>
                              <?php
                      endif;



                 elseif ( is_page() ):

                   if($post->post_parent):
                       $anc = get_post_ancestors( $post->ID );
                       $title = get_the_title();

                       foreach ( $anc as $ancestor ) {
                           $output = ' <div class="ly--breadcrumb-item"><a class="ly--link" href="'.get_permalink($ancestor).'">'.get_the_title($ancestor).'</a></div>';
                       }

                       echo $output;

                         if ( !is_page($frontpage_id) ):?>

                         <div class="ly--breadcrumb-item">
                           <a class="ly--link_current"><?= $title?></a>
                         </div>

                     <?php endif;

                else:

                        if ( !is_page($frontpage_id) ):?>

                        <div class="ly--breadcrumb-item">
                          <a class="ly--link_current"><?= get_the_title();?></a>
                        </div>
                    <?php endif;

                endif;

        endif;

  endif;
?>
    </div>
</nav>
