<button class="ly--btn ly--btn--danger" type="button">Secondary danger button</button>
<button class="ly--btn ly--btn--danger" type="button" disabled>Secondary danger button</button>
<button class="ly--btn ly--btn--danger ly--btn--sm" type="button">Small secondary danger</button>
<button class="ly--btn ly--btn--danger--primary" type="button">Primary Danger button</button>
<button class="ly--btn ly--btn--danger--primary" type="button" disabled>Primary Danger button</button>
<button class="ly--btn ly--btn--danger--primary ly--btn--sm" type="button">Small Primary Danger button</button>
