<button class="ly--btn ly--btn__primary" type="button">Primary button</button>
<button class="ly--btn ly--btn__primary" type="button" disabled>Primary button</button>
<button class="ly--btn ly--btn__primary" type="button">
  Primary with icon
  <svg class="ly--btn__icon" width="16" height="16" viewBox="0 0 16 16" fill-rule="evenodd">
    <path d="M8 0C3.6 0 0 3.6 0 8s3.6 8 8 8 8-3.6 8-8-3.6-8-8-8zm4 9H9v3H7V9H4V7h3V4h2v3h3v2z"></path>
  </svg>
</button>
<button class="ly--btn ly--btn__primary ly--btn--sm" type="button">Small Primary button</button>
<button class="ly--btn ly--btn__primary ly--btn--sm" type="button">
  Small Primary button
  <svg class="ly--btn__icon" width="16" height="16" viewBox="0 0 16 16" fill-rule="evenodd">
    <path d="M8 0C3.6 0 0 3.6 0 8s3.6 8 8 8 8-3.6 8-8-3.6-8-8-8zm4 9H9v3H7V9H4V7h3V4h2v3h3v2z"></path>
  </svg>
</button>


<button class="ly--btn ly--btn__primary_white" type="button">Primary button</button>
<button class="ly--btn ly--btn__primary_secondary" type="button">Primary button</button>
<button class="ly--btn ly--btn__primary_dark" type="button">Primary button</button>
