<?php if( have_rows('our_values') ):

			while( have_rows('our_values') ): the_row();
			// vars
			$heading = get_sub_field('heading');
			$subheading = get_sub_field('subheading');
	?>

	<div class="our-values">

			<div class="our-values--textcontainer">
				<h5 class="our-values__subheading ly--type-epsilon__subheading"><?= $subheading ?></h5>
				<h3 class="our-values__heading ly--type-beta"><?= $heading ?></h3>
			</div>

			<?php if( have_rows('our_values_col') ):?>

					<?php while( have_rows('our_values_col') ): the_row();

								// vars
								$heading = get_sub_field('heading');
								$paragraph = get_sub_field('paragraph');
								$bgimg = get_sub_field('bg_image');
						?>

							<div class="our-values--col" style="background-image: url('<?= $bgimg ?>');">
								<div class="overlay"></div>
								<div class="our-values--circle circle-2">
									<h5 class="our-values__heading ly--type-delta"><?= $heading ?></h5>
									<p class="our-values__paragraph ly--type-epsilon__paragraph"><?= $paragraph ?></p>
								</div>
							</div>

					<?php endwhile; ?>

				<?php endif; ?>

	</div>
	<?php endwhile; ?>

<?php endif; ?>
