<button class="ly--btn ly--btn--secondary" type="button" data-modal-target="#nofooter">Passive</button>

<div data-modal id="nofooter" class="ly--modal" tabindex="-1">
  <div class="ly--modal-container">
    <div class="ly--modal-header">
      <p class="ly--modal-header__label ly--type-delta">Optional label</p>
      <p class="ly--modal-header__heading ly--type-beta">Modal heading</p>
      <button class="ly--modal-close" type="button" data-modal-close data-modal-primary-focus aria-label="close modal">
        <svg class="ly--modal-close__icon" width="10" height="10" viewBox="0 0 10 10" fill-rule="evenodd">
          <title>Close Modal</title>
          <path d="M9.8 8.6L8.4 10 5 6.4 1.4 10 0 8.6 3.6 5 .1 1.4 1.5 0 5 3.6 8.6 0 10 1.4 6.4 5z"></path>
        </svg>
      </button>
    </div>

    <div class="ly--modal-content">
      <p>Passive modal notifications should only appear if there is an action the user needs to address immediately. Passive
        modal notifications are persistent on the screen.</p>
    </div>
  </div>
</div>

<button class="ly--btn ly--btn--danger" type="button" data-modal-target="#nofooter--danger">Passive Danger</button>

<div data-modal id="nofooter--danger" class="ly--modal ly--modal--danger" tabindex="-1">
  <div class="ly--modal-container">
    <div class="ly--modal-header">
      <p class="ly--modal-header__label ly--type-delta">Optional label</p>
      <p class="ly--modal-header__heading ly--type-beta">Modal heading</p>
      <button class="ly--modal-close" type="button" data-modal-close data-modal-primary-focus aria-label="close modal">
        <svg class="ly--modal-close__icon" width="10" height="10" viewBox="0 0 10 10" fill-rule="evenodd">
          <title>Close Modal</title>
          <path d="M9.8 8.6L8.4 10 5 6.4 1.4 10 0 8.6 3.6 5 .1 1.4 1.5 0 5 3.6 8.6 0 10 1.4 6.4 5z"></path>
        </svg>
      </button>
    </div>

    <div class="ly--modal-content">
      <p>Passive modal notifications should only appear if there is an action the user needs to address immediately. Passive
        modal notifications are persistent on the screen.</p>
    </div>
  </div>
</div>
