<section class="ly--structured-list ly--structured-list--border ly--structured-list--selection" data-structured-list>
  <div class="ly--structured-list-thead">
    <div class="ly--structured-list-row ly--structured-list-row--header-row">
      <div class="ly--structured-list-th"></div>
      <div class="ly--structured-list-th">Column A</div>
      <div class="ly--structured-list-th">Column B</div>
      <div class="ly--structured-list-th">Column C</div>
    </div>
  </div>
  <div class="ly--structured-list-tbody">
    <label for="apache-id" aria-label="apache spark" class="ly--structured-list-row ly--structured-list-row--selected" tabindex="0">
      <input tabindex="-1" id="apache-id" class="ly--structured-list-input" value="apache spark" type="radio" name="services" title="apache spark"
        checked />
      <div class="ly--structured-list-td">
        <svg class="ly--structured-list-svg" width="16" height="16" viewBox="0 0 16 16" fill-rule="evenodd">
          <path d="M8 0C3.6 0 0 3.6 0 8s3.6 8 8 8 8-3.6 8-8-3.6-8-8-8zM6.7 11.5L3.4 8.1l1.4-1.4 1.9 1.9 4.1-4.1 1.4 1.4-5.5 5.6z">
          </path>
        </svg>
      </div>
      <div class="ly--structured-list-td ly--structured-list-content--nowrap">Row 1</div>
      <div class="ly--structured-list-td">Row 1</div>
      <div class="ly--structured-list-td">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc dui magna, finibus id tortor sed, aliquet bibendum augue. Aenean posuere sem vel euismod dignissim. Nulla ut cursus dolor. Pellentesque vulputate nisl a porttitor interdum.
      </div>
    </label>
    <label for="cloudant-id" aria-label="Cloudant" class="ly--structured-list-row" tabindex="0">
      <input tabindex="-1" id="cloudant-id" class="ly--structured-list-input" value="Cloudant" type="radio" name="services" title="Cloudant"
      />
      <div class="ly--structured-list-td">
        <svg class="ly--structured-list-svg" width="16" height="16" viewBox="0 0 16 16" fill-rule="evenodd">
          <path d="M8 0C3.6 0 0 3.6 0 8s3.6 8 8 8 8-3.6 8-8-3.6-8-8-8zM6.7 11.5L3.4 8.1l1.4-1.4 1.9 1.9 4.1-4.1 1.4 1.4-5.5 5.6z">
          </path>
        </svg>
      </div>
      <div class="ly--structured-list-td ly--structured-list-content--nowrap">Row 2</div>
      <div class="ly--structured-list-td">Row 2</div>
      <div class="ly--structured-list-td">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc dui magna, finibus id tortor sed, aliquet bibendum augue. Aenean posuere sem vel euismod dignissim. Nulla ut cursus dolor. Pellentesque vulputate nisl a porttitor interdum.</div>
    </label>
    <label for="block-storate-id" aria-label="Cloudant" class="ly--structured-list-row" tabindex="0">
      <input tabindex="-1" id="block-storate-id" class="ly--structured-list-input" value="block-storage" type="radio" name="services"
        title="block-storage" />
      <div class="ly--structured-list-td">
        <svg class="ly--structured-list-svg" width="16" height="16" viewBox="0 0 16 16" fill-rule="evenodd">
          <path d="M8 0C3.6 0 0 3.6 0 8s3.6 8 8 8 8-3.6 8-8-3.6-8-8-8zM6.7 11.5L3.4 8.1l1.4-1.4 1.9 1.9 4.1-4.1 1.4 1.4-5.5 5.6z">
          </path>
        </svg>
      </div>
      <div class="ly--structured-list-td ly--structured-list-content--nowrap">Row 3</div>
      <div class="ly--structured-list-td">Row 3</div>
      <div class="ly--structured-list-td">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc dui magna, finibus id tortor sed, aliquet bibendum augue. Aenean posuere sem vel euismod dignissim. Nulla ut cursus dolor. Pellentesque vulputate nisl a porttitor interdum.</div>
    </label>
    <label for="open-whisk-id" aria-label="Cloudant" class="ly--structured-list-row" tabindex="0">
      <input tabindex="-1" id="open-whisk-id" class="ly--structured-list-input" value="open-whisk" type="radio" name="services" title="open-whisk" />
      <div class="ly--structured-list-td">
        <svg class="ly--structured-list-svg" width="16" height="16" viewBox="0 0 16 16" fill-rule="evenodd">
          <path d="M8 0C3.6 0 0 3.6 0 8s3.6 8 8 8 8-3.6 8-8-3.6-8-8-8zM6.7 11.5L3.4 8.1l1.4-1.4 1.9 1.9 4.1-4.1 1.4 1.4-5.5 5.6z">
          </path>
        </svg>
      </div>
      <div class="ly--structured-list-td ly--structured-list-content--nowrap">Row 4</div>
      <div class="ly--structured-list-td">Row 4</div>
      <div class="ly--structured-list-td">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc dui magna, finibus id tortor sed, aliquet bibendum augue. Aenean posuere sem vel euismod dignissim. Nulla ut cursus dolor. Pellentesque vulputate nisl a porttitor interdum.</div>
    </label>
  </div>
</section>
