<fieldset class="ly--fieldset">
  <legend class="ly--label">Radio Button heading</legend>
  <div class="ly--form-item">
    <div class="ly--radio-button-group">
      <input id="radio-button-1" class="ly--radio-button" type="radio" value="red" name="radio-button" tabindex="0" checked>
      <label for="radio-button-1" class="ly--radio-button__label">
        <span class="ly--radio-button__appearance"></span>
        Radio Button label
      </label>
      <input id="radio-button-2" class="ly--radio-button" type="radio" value="green" name="radio-button" tabindex="0">
      <label for="radio-button-2" class="ly--radio-button__label">
        <span class="ly--radio-button__appearance"></span>
        Radio Button label
      </label>
      <input id="radio-button-3" class="ly--radio-button" type="radio" value="blue" name="radio-button" tabindex="0" disabled>
      <label for="radio-button-3" class="ly--radio-button__label">
        <span class="ly--radio-button__appearance"></span>
        Radio Button label
      </label>
    </div>
  </div>
</fieldset>
