<div class="ly--form-item">
  <label for="text-input-1" class="ly--label">Text Input label</label>
  <input id="text-input-1" type="text" class="ly--text-input" placeholder="Placeholder text">
</div>

<div class="ly--form-item">
  <label for="text-input-2" class="ly--label ly--label--disabled">Text Input label</label>
  <input id="text-input-2" type="text" class="ly--text-input" placeholder="Placeholder text" disabled>
</div>
