<div class="ly--form-item ly--combo-box ly--list-box ly--list-box--disabled">
  <div role="button" class="ly--list-box__field" tabindex="0" aria-label="open menu" aria-expanded="false" aria-haspopup="true" disabled="">
    <input class="ly--text-input" role="combobox" aria-autocomplete="list" aria-expanded="false" autocomplete="off" value="" disabled="" id="downshift-input-13" placeholder="Filter...">
    <div class="ly--list-box__menu-icon">
      <svg fill-rule="evenodd" height="5" name="caret--down" role="img" viewBox="0 0 10 5" width="10" aria-label="Open menu">
        <title>Open menu</title>
        <path d="M10 0L5 5 0 0z"></path>
      </svg>
    </div>
  </div>
</div>
