<?php if( have_rows('section_about-us') ):

	while( have_rows('section_about-us') ): the_row();

		// vars
    $subheading = get_sub_field('subheading');
    $heading = get_sub_field('heading');
    $paragraph = get_sub_field('paragraph');
		$btnprimary = get_sub_field('btn_primary');
		$urlprimary = $btnprimary["url"];
		$labelprimary = $btnprimary["title"];
		$btnsecondary = get_sub_field('btn_secondary');
		$urlsecondary = $btnsecondary["url"];
		$labelsecondary = $btnsecondary["title"];
    ?>

<div class="bx--grid section-about-us section-4rem">
  <div class="bx--row">
    <div class="bx--col-lg-12 section-heading">
      <h5 class="bx--type-delta__subheading"><?= $subheading ?></h5>
      <h2 class="bx--type-alpha"><?= $heading ?></h2>

    </div>
    <div class="bx--col-lg-6 bx--col-md-12 about-us--content">

	<?php if ( have_rows('card_aboutus') ):
					$i = 1;

					while ( have_rows('card_aboutus') ): the_row();
						$subheading = get_sub_field('subheading');
						$description = get_sub_field('description');
						$icon = get_sub_field('icon');

				?>

	        <div class="card card-aboutus card-aboutus-<?= $i++ ?> interactive">
	          <div class="card-aboutus--title-container">
							<div class="card--icon">
								<img class="card--icon__icon" src="<?= $icon ?>" />
							</div>
							<h5 class="bx--type-delta__subheading">
								<?= $subheading ?>
							</h5>
						</div>
	            <p class="bx--type-epsilon__paragraph"><?= $description ?></p>

	        </div>
			<?php endwhile;
					endif;
				?>

				<p><?= $paragraph ?></p>

	      <div class="padding-top">
	        <a href="<?= $urlprimary ?>"><button class="bx--btn bx--btn__primary" type="button"><?= $labelprimary ?></button></a>
					<a href="<?= $urlsecondary ?>"><button class="bx--btn bx--btn--outline" type="button"><?= $labelsecondary ?></button></a>
	      </div>


    </div>
    <div class="bx--col-lg-6 bx--col-md-12 about-us--circle">

      <div class="interactive-circle">

        <div class="circle-inner">

          <div class="circle-sm center">
            <svg width="64" height="52" viewBox="0 0 64 52">
              <g fill="none" fill-rule="evenodd">
                <polygon fill="#FF6665" points="53.811 34.66 60.03 51.708 63.816 51.708 63.816 34.66"/>
                <polygon fill="#1A1A1A" points="18.912 0 .019 51.688 0 51.708 .012 51.708 17.004 51.708 36.548 51.708 34.346 44.405 31.438 34.66 22.114 34.66 22.655 32.845 28.123 14.423 28.454 14.423 33.848 32.845 37.297 44.405 39.499 51.708 57.078 51.708 38.215 0"/>
              </g>
            </svg>
          </div>

          <a href="javascript:void(0)" data-tooltip-trigger data-tooltip-target="#circle-sm-1" class="circle-sm circle-sm-1 icon icn-growthanalysis--simple active deg0">
            <svg width="24" height="24" viewBox="0 0 24 24">
              <g fill-rule="evenodd">
                <polygon points="18 22 20 24 24 20 22 18"/>
                <path d="M7.9995,10.0005 L9.9995,12.0005 L15.3385,6.6625 C15.7575,7.5205 15.9995,8.4815 15.9995,9.5005 C15.9995,13.0845 13.0835,16.0005 9.4995,16.0005 C7.4545,16.0005 5.6275,15.0465 4.4355,13.5645 L7.9995,10.0005 Z M14.5645,5.4355 L9.9995,10.0005 L7.9995,8.0005 L3.6615,12.3375 C3.2425,11.4795 2.9995,10.5185 2.9995,9.5005 C2.9995,5.9165 5.9155,3.0005 9.4995,3.0005 C11.5455,3.0005 13.3725,3.9535 14.5645,5.4355 Z M18.9995,15.0005 L17.9105,13.9105 C18.6035,12.5915 18.9995,11.0925 18.9995,9.5005 C18.9995,4.2525 14.7475,0.0005 9.4995,0.0005 C4.2525,0.0005 -0.0005,4.2525 -0.0005,9.5005 C-0.0005,14.7475 4.2525,19.0005 9.4995,19.0005 C11.0925,19.0005 12.5915,18.6035 13.9105,17.9105 L14.9995,19.0005 L18.9995,15.0005 Z"/>
                <polygon points="21 18 19 16 16 19 18 21"/>
              </g>
            </svg>
						<div id="circle-sm-1" data-floating-menu-direction="bottom" class="bx--tooltip">
						  <p>Tillväxtanalys</p>
						</div>
          </a>
          <a href="javascript:void(0)" data-tooltip-trigger data-tooltip-target="#circle-sm-2" class="circle-sm circle-sm-2 icon icn-bulb deg72">
            <svg width="20" height="26" viewBox="0 0 20 26">
              <g fill-rule="evenodd">
                <path d="M3,10 C3,6.141 6.141,3 10,3 C13.859,3 17,6.141 17,10 C17,11.958 16.189,13.729 14.89,15 L5.11,15 C3.811,13.729 3,11.958 3,10 M20,10 C20,4.478 15.523,0 10,0 C4.477,0 0,4.478 0,10 C0,13.268 1.576,16.16 4,17.984 L4,18 L4.018,18 L15.982,18 L16,18 L16,17.984 C18.424,16.16 20,13.268 20,10"/>
                <polygon points="5 22 15 22 15 19 5 19"/>
                <polygon points="7 26 13 26 13 23 7 23"/>
              </g>
            </svg>
						<div id="circle-sm-2" data-floating-menu-direction="bottom" class="bx--tooltip">
							<p>Skapa hypoteser</p>
						</div>

          </a>
          <a href="javascript:void(0)" data-tooltip-trigger data-tooltip-target="#circle-sm-3" class="circle-sm circle-sm-3 icon icn-testing deg144">
            <svg width="24" height="24" viewBox="0 0 24 24">
              <g fill-rule="evenodd">
                <polygon points="21 6 21 6 18 9 18 7 16 7 16 11 14 13 16 15 23 8 23 4 21 4"/>
                <polygon points="4 0 0 4.001 2 4.001 2 8 11 17 11 24 15.001 24 15.001 16 6.001 7 6.001 4.001 8.001 4.001"/>
                <polygon points="15 6 19 6 19 5 15 5"/>
                <polygon points="20 3 24 3 24 2 20 2"/>
              </g>
            </svg>
						<div id="circle-sm-3" data-floating-menu-direction="bottom" class="bx--tooltip">
							<p>Testa småskaligt</p>
						</div>

          </a>
          <a href="javascript:void(0)" data-tooltip-trigger data-tooltip-target="#circle-sm-4" class="circle-sm circle-sm-4 icon icn-measure deg216">
            <svg width="24" height="25" viewBox="0 0 24 25">
              <g fill-rule="evenodd" transform="translate(0 1)">
                <polygon points="0 0 0 15 8 15 8 14 6 14 6 13.001 8 13.001 8 10 6 10 6 9 8 9 8 6 6 6 6 5 8 5 8 2.001 4 2.001 4 1 8 1 8 0"/>
                <polygon points="23 16 23 20.001 21.999 20.001 21.999 16 18.999 16 18.999 18 18 18 18 16 15 16 15 18 14 18 14 16 10.999 16 10.999 18 9.999 18 9.999 16 0 16 0 24 24 24 24 16"/>
              </g>
            </svg>
						<div id="circle-sm-4" data-floating-menu-direction="bottom" class="bx--tooltip">
							<p>Mäta & analysera</p>
						</div>

          </a>
          <a href="javascript:void(0)" data-tooltip-trigger data-tooltip-target="#circle-sm-5" class="circle-sm circle-sm-5 icon icn-iterate deg288">
            <svg width="24" height="24" viewBox="0 0 24 24">
              <path fill-rule="evenodd" d="M11.9746457,0 C8.65459058,0 5.66122969,1.356 3.48560649,3.529 L1.95335044,2 L1.95335044,7 L6.96399807,7 L5.61513173,5.654 C7.24760073,4.023 9.48836234,3 11.9746457,3 C16.9482145,3 20.9938114,7.037 20.9938114,12 C20.9938114,16.963 16.9482145,21 11.9746457,21 C7.34079877,21 3.51567037,17.493 3.01460561,13 L0.0002,13 C0.510283928,19.158 5.67125098,24 11.9746457,24 C18.6157581,24 24.0002,18.627 24.0002,12 C24.0002,5.373 18.6157581,0 11.9746457,0"/>
            </svg>
          </a>
					<div id="circle-sm-5" data-floating-menu-direction="bottom" class="bx--tooltip">
						<p>Justera & iterera</p>
					</div>

        </div>

        <div class="circle-middle"></div>
        <div class="circle-outer"></div>

      </div>

    </div>

  </div>
</div>

<?php endwhile; ?>

<?php endif; ?>
