<?php

// Vars
$formheading = get_sub_field('form_heading');
$formparagraph = get_sub_field('form_paragraph');
$selectcolor = get_sub_field('form_color');

?>

<div class="component ly--contact-form">

  <div class="contact-form--container">

    <div class="card form no-link">

          <div class="ly--col-lg-12 ly--col-xs-12 contact-form--col">
            <h3 class="contact-form--col__heading ly--type-beta"><?= $formheading ?></h3>
            <p class="contact-form--col__paragraph ly--type-delta__paragraph"><?= $formparagraph ?></p>
          </div>

          <div class="ly--col-lg-6 ly--col-md-3 ly--col-xs-12 contact-form--col">
            <?php echo do_shortcode('[contact-form-7 id="518" title="Contact form - Default" html_class="ly--form-item"]'); ?>
          </div>
      </div>
  </div>

  <div class="bg-<?php echo $selectcolor ? $selectcolor : 'primary'; ?>"></div>

</div>
