<?php if( have_rows('soft_cta') ):?>

  <div class="grid component soft-cta">
    <div class="grid-container component--outer">

      <div class="component--container">

        <?php while( have_rows('soft_cta') ): the_row();

        // Stat + info
        $img = get_sub_field('image');
        $text = get_sub_field('text');
        $link = get_sub_field('link');
        $url = $link['url'];
        $label = $link['title'];

          ?>

        <a class="card__link" href="<?= $url ?>">

            <div class="card card--soft-cta">

              <div class="soft-cta--img-container">
                <?php add_image($img, '', 'soft-cta__image'); ?>
              </div>

              <div class="soft-cta--text-container">
                <p class="soft-cta__text paragraph"><?= $text ?></p>
                <span class="soft-cta__link paragraph" href="<?= $url ?>"><?= $label ?></span>
              </div>

            </div>

          </a>

        <?php endwhile; ?>

        </div>
      </div>
    </div>
<?php endif; ?>
