<?php if( have_rows('section-services') ):

	while( have_rows('section-services') ): the_row();

		// vars
    $subheading = get_sub_field('subheading');
    $heading = get_sub_field('heading');
    $btnlabel = get_sub_field('btn_label');
    $btnlink = get_sub_field('btn_link');

		?>
    <div class="bx--grid services-sm section-6rem">
      <div class="bx--row">
        <div class="bx--col-lg-12 section-heading">
          <h5 class="bx--type-delta_subheading"><?= $subheading ?></h5>
          <h2 class="bx--type-alpha"><?= $heading ?></h2>
        </div>
        <div class="bx--col-lg-12 section-wrap">

          <?php
                $args = array(
                    'post_type' => 'services',
                    'orderby' => 'title',
                    'order'   => 'DESC',
                    'posts_per_page' => -1,
                );

                $query = new WP_Query( $args );
                ?>

                <?php while ( $query->have_posts() ) : $query->the_post();

                  include( get_template_directory() . '/phtml/sections/cards/card-service-sm.phtml');

                endwhile; ?>

                <?php
                wp_reset_postdata();?>

        </div>
        <div class="bx--col-lg-12 padding-top">
          <a href="<?= $btnlink ?>"><button class="bx--btn bx--btn--primary" type="button"><?= $btnlabel ?></button></a>
        </div>

      </div>
    </div>
	<?php endwhile; ?>

<?php endif; ?>
