<div class="bx--grid widgets section-4rem">
  <div class="bx--row">

    <!--Widget 1-->
    <div class="widget widget-1 section-4col">
      <img class="widget-logo" src="<?= the_field('widget_one','option'); ?>" />
    </div>

    <!--Widget 1-->
    <div class="widget widget-2 section-4col">
      <h1>widget 2</h1>
    </div>

    <!--Widget 1-->
    <div class="widget widget-3 section-4col">
      <h1>widget 3</h1>
    </div>

    <!--Widget 4-->
    <div class="widget widget-4 ">
      <h1>widget 4</h1>
    </div>

  </div>

</div>
