<div class="our-values">
	<div class="our-values--textcontainer">
		<h5 class="our-values__subheading bx--type-epsilon__subheading">Våra värderingar</h5>
		<h3 class="our-values__heading bx--type-beta">Hur vi ger data liv</h3>
	</div>
	<div class="our-values--col">
		<div class="overlay"></div>
		<div class="our-values--circle circle-1">
			<h5 class="our-values__heading bx--type-delta">Teamwork</h5>
			<p class="our-values__paragraph bx--type-epsilon__paragraph">Ingen är en ensam ö. Vi tror på gemenskap och vikten av att dela erfarenheter och uppmuntra varandra.</p>
		</div>
	</div>
	<div class="our-values--col">
		<div class="overlay"></div>
		<div class="our-values--circle circle-2">
			<h5 class="our-values__heading bx--type-delta"><?= $subheading ?></h5>
			<p class="our-values__paragraph bx--type-epsilon__paragraph"><?= $heading ?></p>
		</div>
	</div>
	<div class="our-values--col">
		<div class="overlay"></div>
		<div class="our-values--circle circle-2">
			<h5 class="our-values__heading bx--type-delta"><?= $subheading ?></h5>
			<p class="our-values__paragraph bx--type-epsilon__paragraph"><?= $heading ?></p>
		</div>
	</div>
</div>
