<div class="bx--grid why-us section-8rem">
	<div class="bx--row">

		<div class="bx--col-lg-12 section-heading_center">
			<h5 class="bx--type-epsilon__subheading">Våra värderingar</h5>
			<h3 class="bx--type-beta">Hur vi ger data liv</h3>
		</div>

		<div class="bx--col-xs-6 bx--col-md-4 bx--col-lg-3 bx--col-xl-2 why-us--col">
			<div class="why-us__icon"></div>
			<h5 class="why-us__heading bx--type-delta__paragraph">Something</h5>
			<p class="why-us__paragraph bx--type-zeta">En paragraf bla bla bla</p>
		</div>

		<div class="bx--col-xs-6 bx--col-md-4 bx--col-lg-3 bx--col-xl-2 why-us--col">
			<div class="why-us__icon"></div>
			<h5 class="why-us__heading bx--type-delta__paragraph">Something</h5>
			<p class="why-us__paragraph bx--type-zeta">En paragraf bla bla bla</p>
		</div>

		<div class="bx--col-xs-6 bx--col-md-4 bx--col-lg-3 bx--col-xl-2 why-us--col">
			<div class="why-us__icon"></div>
			<h5 class="why-us__heading bx--type-delta__paragraph">Something</h5>
			<p class="why-us__paragraph bx--type-zeta">En paragraf bla bla bla</p>
		</div>

		<div class="bx--col-xs-6 bx--col-md-4 bx--col-lg-3 bx--col-xl-2 why-us--col">
			<div class="why-us__icon"></div>
			<h5 class="why-us__heading bx--type-delta__paragraph">Something</h5>
			<p class="why-us__paragraph bx--type-zeta">En paragraf bla bla bla</p>
		</div>

		<div class="bx--col-xs-6 bx--col-md-4 bx--col-lg-3 bx--col-xl-2 why-us--col">
			<div class="why-us__icon"></div>
			<h5 class="why-us__heading bx--type-delta__paragraph">Something</h5>
			<p class="why-us__paragraph bx--type-zeta">En paragraf bla bla bla</p>
		</div>

		<div class="bx--col-xs-6 bx--col-md-4 bx--col-lg-3 bx--col-xl-2 why-us--col">
			<div class="why-us__icon"></div>
			<h5 class="why-us__heading bx--type-delta__paragraph">Something</h5>
			<p class="why-us__paragraph bx--type-zeta">En paragraf bla bla bla</p>
		</div>

	</div>
</div>
