<div class="ly--form-item">
  <label for="number-input" class="ly--label">Number Input label</label>
  <div data-numberinput class="ly--number">
    <input id="number-input" type="number" min="0" max="100" value="1">
    <div class="ly--number__controls">
      <button class="ly--number__control-btn up-icon">
        <svg viewBox="0 2 10 5" width="10" height="5" fill-rule="evenodd">
          <path d="M10 5L5 0 0 5z"></path>
        </svg>
      </button>
      <button class="ly--number__control-btn down-icon">
        <svg viewBox="0 2 10 5" width="10" height="5" fill-rule="evenodd">
          <path d="M10 0L5 5 0 0z"></path>
        </svg>
      </button>
    </div>
  </div>
</div>

<div class="ly--form-item">
  <label for="number-input" class="ly--label">Number Input label</label>
  <div data-invalid data-numberinput class="ly--number">
    <input id="number-input" type="number" min="0" max="100" value="1">
    <div class="ly--number__controls">
      <button class="ly--number__control-btn up-icon">
        <svg viewBox="0 2 10 5" width="10" height="5" fill-rule="evenodd">
          <path d="M10 5L5 0 0 5z"></path>
        </svg>
      </button>
      <button class="ly--number__control-btn down-icon">
        <svg viewBox="0 2 10 5" width="10" height="5" fill-rule="evenodd">
          <path d="M10 0L5 5 0 0z"></path>
        </svg>
      </button>
    </div>
  </div>
  <div class="ly--form-requirement">
    Invalid number
  </div>
</div>
