<article class="ly--card" tabindex="0" aria-labelledby="card-title-2">
  <div class="ly--card__card-overview">
    <!-- OverflowMenu -->
    <div data-overflow-menu class="ly--overflow-menu" tabindex="0" aria-label="List of options">
      <svg class="ly--overflow-menu__icon" width="4" height="20" viewBox="0 0 4 20" fill-rule="evenodd">
        <title>list of options</title>
        <circle cx="2" cy="2" r="2"></circle>
        <circle cx="2" cy="10" r="2"></circle>
        <circle cx="2" cy="18" r="2"></circle>
      </svg>
      <ul class="ly--overflow-menu-options">
        <li class="ly--overflow-menu-options__option">
          <button type="button" class="ly--overflow-menu-options__btn">Stop App</button>
        </li>
        <li class="ly--overflow-menu-options__option">
          <button type="button" class="ly--overflow-menu-options__btn">Restart App</button>
        </li>
        <li class="ly--overflow-menu-options__option">
          <button type="button" class="ly--overflow-menu-options__btn">Restart App</button>
        </li>
        <li class="ly--overflow-menu-options__option">
          <button type="button" class="ly--overflow-menu-options__btn">Edit Routes and Access</button>
        </li>
        <li class="ly--overflow-menu-options__option ly--overflow-menu--divider">
          <button type="button" class="ly--overflow-menu-options__btn">Delete App</button>
        </li>
      </ul>
    </div>
    <section class="ly--card-overview__about">
      <figure class="ly--about__icon">
        <img src="/globals/assets/images/placeholder-icon-32x32.svg" alt="" class="ly--about__icon--img" />
      </figure>
      <header class="ly--about__title">
        <p id="card-title-2" class="ly--about__title--name ly--type-gamma" title="Card Name">Card Name</p>
        <p class="ly--about__title--additional-info ly--type-delta" title="Secondary Information">Secondary Information</p>
      </header>
  </div>
  </section>
  <footer class="ly--card-footer">
    <button class="ly--btn ly--btn__primary ly--btn--sm" type="button" title="View credentials">View credentials</button>
    <a href="" class="ly--card-footer__link">Docs</a>
  </footer>
</article>
